### ISSUE TITLE
Wrong user IP when nginx proxy is used

### ISSUE THREAD

**Issue by liminspace** [docker-library/redmine#104]
How can I get real IP in log if I use nginx proxy?

**Comment by tianon** [comment]
This sounds like https://www.redmine.org/issues/11277 (and thus the issues linked there are probably highly relevant).  I'd imagine it _should_ work if you set `X-Forwarded-For` in the NGINX layer (which is a good practice to follow generally), but looks like that depends on Rails. :disappointed:

It _might_ require setting `trusted_proxies` directly, ala https://github.com/rails/rails/pull/2632.

Regardless, this is definitely an upstream (or configuration) issue and unfortunately not something to fix in the image.  Sorry!
