### ISSUE TITLE
ActionView::Template::Error (undefined method `default_users_time_zone')

### ISSUE THREAD

**Issue by prohde** [docker-library/redmine#107]
Every thing worked fine for me with Redmine 3.3. Now I wanted to upgrade to 3.4.4 and Redmine is no longer running. I searched the internet but did not find the exact same problem. Similar problems where caused by plugins but I do not have any plugins installed. I use the Passenger Docker image of Redmine.

The logs give me the following error message:

    Processing by WelcomeController#index as HTML
      Current user: anonymous
    Redirected to http://0.0.0.0/login?back_url=http%3A%2F%2F0.0.0.0%2F
    Filter chain halted as :check_if_login_required rendered or redirected
    Completed 302 Found in 60ms (ActiveRecord: 3.7ms)
    App 179 stdout: 
    Started GET "/login?back_url=https%3A%2F%2Fredmine.mydomain.tld%2F" for 95.90.204.176 at 2018-03-14 19:10:26 +0000
    Processing by AccountController#login as HTML
      Parameters: {"back_url"=>"https://redmine.mydomain.tld/"}
      Current user: anonymous
      Rendered account/login.html.erb within layouts/base (24.1ms)
    Completed 500 Internal Server Error in 219ms (ActiveRecord: 4.3ms)
    
    ActionView::Template::Error (undefined method `default_users_time_zone' for #<Class:0x00000000055f2120>
    Did you mean?  default_users_hide_mail):
        11: <%= favicon %>
        12: <%= stylesheet_link_tag 'jquery/jquery-ui-1.11.0', 'application', 'responsive', :media => 'all' %>
        13: <%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
        14: <%= javascript_heads %>
        15: <%= heads_for_theme %>
        16: <%= call_hook :view_layouts_base_html_head %>
        17: 
      app/models/user_preference.rb:44:in `initialize'
      app/models/user.rb:949:in `pref'
      app/helpers/application_helper.rb:1451:in `javascript_heads'
      app/views/layouts/base.html.erb:14:in `_app_views_layouts_base_html_erb__2446195152155203147_36658300'
      lib/redmine/sudo_mode.rb:63:in `sudo_mode'

What could that be? I need to upgrade to 3.4 because I want to use a plugin but the plugin requires version 3.4 in use.

**Comment by prohde** [comment]
I got it working. I missed to replace one of the config files with the new one. What a shame!

**Comment by konandrum** [comment]
Which one ? Get the same error :(
