### ISSUE TITLE
How to set REDMINE_DB_MYSQL

### ISSUE THREAD

**Issue by gdgeorge** [docker-library/redmine#113]
On a Ubuntu 18 virtualbox with a mysql server running, I'm trying to start Redmine with the following command (with or without the = after REDMINE_DB_MYSQL):

`docker run -dit --restart always --name redmine -p 3000:3000 -v /var/redmine/data:/home/redmine/data -e REDMINE_DB_MYSQL= -e REDMINE_DB_NAME='redmine' -e REDMINE_DB_USER='redmine' -e REDMINE_DB_PASS='redmine!23' library/redmine:3.3.7`

This leads to errors with REDMINE_DB_MYSQL not being found:

```
08T21:30:21.531443647Z 
08T21:30:21.531489012Z warning: missing REDMINE_DB_MYSQL, REDMINE_DB_POSTGRES, or REDMINE_DB_SQLSERVER environment variables
08T21:30:21.531493721Z 

08T21:30:21.531496606Z *** Using sqlite3 as fallback. ***
08T21:30:21.531499362Z 

```
If I try and assign a value to REDMINE_DB_MYSQL such as mysql or MYSQL or 0, 1, etc, the container tosses:
```
08T21:33:35.719314576Z The Gemfile's dependencies are satisfied
08T21:33:38.726693179Z rake aborted!
08T21:33:38.726731301Z Mysql2::Error: Unknown MySQL server host 'MYSQL' (25)
```
Pretty sure I'm missing something obvious here, but just how is REDMINE_DB_MYSQL to be declared?

Thanks,
Jerry

**Comment by wglambert** [comment]
https://github.com/docker-library/docs/blob/master/redmine/README.md#redmine_db_mysql-or-redmine_db_postgres

> These two variables allow you to set the hostname or IP address of the MySQL or PostgreSQL host

So the 'host' could be a container running mysql, such that you would network them together and then use its hostname (if on the same network), if using `--link` then hostname resolutions for other containers won't work.

And then `-e REDMINE_DB_MYSQL mysql_hostname/address`

**Comment by gdgeorge** [comment]
Thanks for getting back so quickly. I think the documentation needs to explain the possible values for REDMINE_DB_MYSQL. 

Further, I think my issue is actually grounded in your notion of "networking them together." My intent was to let the container access my existing mysql server which runs on the Docker host. 

Jerry

**Comment by maximkrusina** [comment]
@gdgeorge - do You need to run it via docker command, or can you use docker-compose? I can post an working docker-compose.yml file, which is imho much better for organizing Docker projects, than just single docker commands...

**Comment by yosifkit** [comment]
The set of possible values is in the description: "hostname or IP address".  So any resolvable hostname or an IP address should work as long as the container can establish a route to it.

There is also an example in the [stack file section](https://github.com/docker-library/docs/tree/f94c0219150232f285bce7e690c354f08f8e3e2a/redmine#-via-docker-stack-deploy-or-docker-compose):

```yml
version: '3.1'

services:

  redmine:
    image: redmine
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
```
(`db` in this compose file is a dns name created by Docker for these containers to be able to resolve to the IP address of the MySQL container)

**Comment by gdgeorge** [comment]
Thanks for the help folks.  I prefer to run containers from the command line (or Portainer--although that one doesn't support --link, as it's deprecated.  I bit the bullet and started a MariaDB container and am using that for the Redmine container.
