### ISSUE TITLE
No 'New Issue' Tab

### ISSUE THREAD

**Issue by jshdcca** [docker-library/redmine#12]
I did a fresh docker pull then attached it to a MySQL instance.
When I tested it out, I couldnt seem to find the 'New Issue' Tab or button.

I already checked the roles and permissions. Is there some step I missed?

**Comment by yosifkit** [comment]
Anything in the `docker logs` that might be helpful?

**Comment by nviel** [comment]
There is no tracker defined. I had to create at least one before the 'New Issue' tab appears.
I created trackers, workflow and so on.

**Comment by maximkrusina** [comment]
Hi @nviel this can be set in Redmine's config. The default behaviour switched some time ago from "New tab" for issues to the "+" button, which is as the first item in a menu. Personally, I don't like this approach so everytime I'm switching to the "old" behaviour via "New issue" tab / menu item. Does this solve this issue? 

![screen_shot_2018-04-21_at_09_31_47](https://user-images.githubusercontent.com/201688/39081769-92943b2c-4547-11e8-9a32-882863c1ae49.jpg)

**Comment by tianon** [comment]
Nice catch -- closing since this appears to be resolved. :+1:
