### ISSUE TITLE
Missing run dependencies

### ISSUE THREAD

**Issue by J0WI** [docker-library/redmine#120]
STR:
1. start Redmine conatiner
2. login and go to administration > information
```
sh: 1: convert: not found
sh: 1: darcs: not found
sh: 1: cvs: not found
failed to open trace file: [Errno 2] No such file or directory: '/home/redmine/.bzr.log'
```

I assume that these binaries should not be removed.

**Comment by yosifkit** [comment]
- `convert` looks like that was lost in https://github.com/docker-library/redmine/pull/116 (we should probably fix that)
- `darcs` and `cvs` were dropped in https://github.com/docker-library/redmine/commit/54bd741252abf1856ae79b2501752b2ac96ab215 and so probably never in a built image

**Comment by J0WI** [comment]
See #121 for `convert`.

**Comment by tianon** [comment]
Given that #121 added `convert` and that `darcs` and `cvs` are ancient (and not something we should bother installing in 2018 IMO), I'm going to close this.

If this is causing any serious functionality issues in Redmine itself, I'll happily reconsider. :+1:
