### ISSUE TITLE
Help upgrading to new version.

### ISSUE THREAD

**Issue by marciofoz** [docker-library/redmine#139]
Hi !! 
I have in production Redmine 2.3 (Centos 7+Mysql) and would like move to Docker container with a newer version.  For tests propose, I dump the Mysql database and restore it in other server.
When I start the container, I hope the database is converted to this new version, but I'm getting this errors, and others tables are getting empty.

Does the migration job will not convert from the older version (2.3) to the new version (3.4) ?

I'm using Fedora 28:

$ sudo docker run -it -e REDMINE_DB_DATABASE=redmine -e REDMINE_DB_PASSWORD=menina -e REDMINE_DB_USERNAME=redmine -e REDMINE_DB_PORT=3306 -e REDMINE_DB_MYSQL=10.80.14.14 -e REDMINE_PLUGINS_MIGRATE=true  --name redemine redmine 
`/home/redmine` is not a directory.
Bundler will use `/tmp/bundler/home/unknown' as your home directory temporarily.
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.
The Gemfile's dependencies are satisfied
== 1 Setup: migrating =========================================================
-- create_table("attachments", {:force=>true})
   -> 0.0704s
-- create_table("auth_sources", {:force=>true})
   -> 0.0774s
-- create_table("custom_fields", {:force=>true})
   -> 0.0750s
-- create_table("custom_fields_projects", {:id=>false, :force=>true})
   -> 0.0746s
-- create_table("custom_fields_trackers", {:id=>false, :force=>true})
   -> 0.0764s
-- create_table("custom_values", {:force=>true})
   -> 0.0741s
-- create_table("documents", {:force=>true})
   -> 0.0773s
-- add_index("documents", ["project_id"], {:name=>"documents_project_id"})
   -> 0.0332s
-- create_table("enumerations", {:force=>true})
   -> 0.0736s
-- create_table("issue_categories", {:force=>true})
   -> 0.0773s
-- add_index("issue_categories", ["project_id"], {:name=>"issue_categories_project_id"})
   -> 0.0317s
-- create_table("issue_histories", {:force=>true})
   -> 0.0413s
-- add_index("issue_histories", ["issue_id"], {:name=>"issue_histories_issue_id"})
   -> 0.0470s
-- create_table("issue_statuses", {:force=>true})
   -> 0.0739s
-- create_table("issues", {:force=>true})
   -> 0.0784s
-- add_index("issues", ["project_id"], {:name=>"issues_project_id"})
   -> 0.0336s
-- create_table("members", {:force=>true})
   -> 0.0729s
-- create_table("news", {:force=>true})
   -> 0.0774s
-- add_index("news", ["project_id"], {:name=>"news_project_id"})
   -> 0.0335s
-- create_table("permissions", {:force=>true})
   -> 0.0401s
-- create_table("permissions_roles", {:id=>false, :force=>true})
   -> 0.0427s
-- add_index("permissions_roles", ["role_id"], {:name=>"permissions_roles_role_id"})
   -> 0.0442s
-- create_table("projects", {:force=>true})
   -> 0.0741s
-- create_table("roles", {:force=>true})
   -> 0.0779s
-- create_table("tokens", {:force=>true})
   -> 0.0748s
-- create_table("trackers", {:force=>true})
   -> 0.0744s
-- create_table("users", {:force=>true})
   -> 0.0768s
-- create_table("versions", {:force=>true})
   -> 0.0734s
-- add_index("versions", ["project_id"], {:name=>"versions_project_id"})
   -> 0.0359s
-- create_table("workflows", {:force=>true})
   -> 0.0738s
== 1 Setup: migrated (2.3162s) ================================================

== 2 IssueMove: migrating =====================================================
== 2 IssueMove: migrated (0.0116s) ============================================

== 3 IssueAddNote: migrating ==================================================
== 3 IssueAddNote: migrated (0.0175s) =========================================

== 4 ExportPdf: migrating =====================================================
== 4 ExportPdf: migrated (0.0198s) ============================================

== 5 IssueStartDate: migrating ================================================
-- add_column(:issues, :start_date, :date)
   -> 0.0762s
-- add_column(:issues, :done_ratio, :integer, {:default=>0, :null=>false})
   -> 0.0748s
== 5 IssueStartDate: migrated (0.1511s) =======================================

== 6 CalendarAndActivity: migrating ===========================================
== 6 CalendarAndActivity: migrated (0.0266s) ==================================

== 7 CreateJournals: migrating ================================================
-- create_table(:journals, {:force=>true})
   -> 0.0755s
-- create_table(:journal_details, {:force=>true})
   -> 0.0737s
-- add_index("journals", ["journalized_id", "journalized_type"], {:name=>"journals_journalized_id"})
   -> 0.0337s
-- add_index("journal_details", ["journal_id"], {:name=>"journal_details_journal_id"})
   -> 0.0357s
-- drop_table(:issue_histories)
   -> 0.0302s
== 7 CreateJournals: migrated (0.2739s) =======================================

== 8 CreateUserPreferences: migrating =========================================
-- create_table(:user_preferences)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Table 'user_preferences' already exists: CREATE TABLE `user_preferences` (`id` int(11) auto_increment PRIMARY KEY, `user_id` int(11) DEFAULT 0 NOT NULL, `others` text) ENGINE=InnoDB
/usr/local/bundle/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `_query'
/usr/local/bundle/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `block in query'
/usr/local/bundle/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `handle_interrupt'
/usr/local/bundle/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `query'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `block in execute'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `execute'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/mysql2_adapter.rb:225:in `execute'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/schema_statements.rb:222:in `create_table'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:474:in `create_table'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:665:in `block in method_missing'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `block in say_with_time'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `say_with_time'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:654:in `method_missing'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:416:in `method_missing'
/usr/src/redmine/db/migrate/008_create_user_preferences.rb:3:in `up'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:571:in `up'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:611:in `exec_migration'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:591:in `block in migrate'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:590:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:768:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:1046:in `ddl_transaction'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:959:in `block in migrate'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `each'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:823:in `up'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:801:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'

Caused by:
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'user_preferences' already exists: CREATE TABLE `user_preferences` (`id` int(11) auto_increment PRIMARY KEY, `user_id` int(11) DEFAULT 0 NOT NULL, `others` text) ENGINE=InnoDB
/usr/local/bundle/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `_query'
/usr/local/bundle/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `block in query'
/usr/local/bundle/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `handle_interrupt'
/usr/local/bundle/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `query'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `block in execute'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `execute'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/mysql2_adapter.rb:225:in `execute'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/schema_statements.rb:222:in `create_table'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:474:in `create_table'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:665:in `block in method_missing'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `block in say_with_time'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `say_with_time'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:654:in `method_missing'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:416:in `method_missing'
/usr/src/redmine/db/migrate/008_create_user_preferences.rb:3:in `up'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:571:in `up'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:611:in `exec_migration'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:591:in `block in migrate'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:590:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:768:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:1046:in `ddl_transaction'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:959:in `block in migrate'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `each'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:823:in `up'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:801:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'

Caused by:
Mysql2::Error: Table 'user_preferences' already exists
/usr/local/bundle/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `_query'
/usr/local/bundle/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `block in query'
/usr/local/bundle/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `handle_interrupt'
/usr/local/bundle/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `query'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `block in execute'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `execute'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/mysql2_adapter.rb:225:in `execute'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/schema_statements.rb:222:in `create_table'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:474:in `create_table'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:665:in `block in method_missing'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `block in say_with_time'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `say_with_time'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:654:in `method_missing'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:416:in `method_missing'
/usr/src/redmine/db/migrate/008_create_user_preferences.rb:3:in `up'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:571:in `up'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:611:in `exec_migration'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:591:in `block in migrate'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:590:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:768:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:1046:in `ddl_transaction'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:959:in `block in migrate'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `each'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:823:in `up'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:801:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by yosifkit** [comment]
The image only runs `rake db:migrate`, so if that doesn't work to upgrade your database, then that is a question for other redmine users. You might try the [redmine user boards](https://www.redmine.org/projects/redmine/boards).  It does seem similar to https://www.redmine.org/boards/2/topics/50880 but I didn't see a solution there.

Since this isn't really a problem with the image, but with redmine itself I will close.
