### ISSUE TITLE
can't use chinese language to create project

### ISSUE THREAD

**Issue by Kevalin** [docker-library/redmine#145]
I use default config to run the container.I can vist redmine website successfilly , but i can't create a project that take a  chinese name.

**Comment by Kevalin** [comment]
fixed.

like this start mysql

```bash
docker run -d -p 3306:3306 --name mysql5.7 -e MYSQL_ROOT_PASSWORD=123456 -e MYSQL_DATABASE=redmine mysql:5.7 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
```

**Comment by wglambert** [comment]
Closing since this is resolved 

Reference for these client options https://dev.mysql.com/doc/refman/5.7/en/charset-applications.html

And an example is in the `mysql` [ docs ](https://github.com/docker-library/docs/tree/master/mysql#configuration-without-a-cnf-file)
```console
$ docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mysql:tag --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
```

**Comment by Kevalin** [comment]
> Closing since this is resolved
> 
> Reference for these client options https://dev.mysql.com/doc/refman/5.7/en/charset-applications.html
> 
> And an example is in the `mysql` [ docs ](https://github.com/docker-library/docs/tree/master/mysql#configuration-without-a-cnf-file)
> 
> ```
> $ docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mysql:tag --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
> ```

👍👍👍
