### ISSUE TITLE
How to bind configuration.yml

### ISSUE THREAD

**Issue by heymis** [docker-library/redmine#155]
I made configuration.yml and bind path /usr/src/redmine/config/configuration.yml for image redmine:4.0.1, it causes error.

```
default:
   email_delivery:
     delivery_method: :smtp
     smtp_settings:
        enable_starttls_auto: true
        address: "smtp.gmail.com"
        port: 587
        domain: "smtp.gmail.com"
        authentication: :plain
        user_name: "your_email@gmail.com"
        password: "your_password"
```

Error Message:

redmine    | The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.
redmine    | The Gemfile's dependencies are satisfied
redmine    | rake aborted!
redmine    | Psych::SyntaxError: (<unknown>): mapping values are not allowed in this context at line 4 column 20
redmine    | /usr/src/redmine/lib/redmine/configuration.rb:92:in `load_from_yaml'
redmine    | /usr/src/redmine/lib/redmine/configuration.rb:42:in `load'
redmine    | /usr/src/redmine/lib/redmine/configuration.rb:73:in `[]'
redmine    | /usr/src/redmine/lib/redmine/thumbnail.rb:25:in `<module:Thumbnail>'
redmine    | /usr/src/redmine/lib/redmine/thumbnail.rb:22:in `<module:Redmine>'
redmine    | /usr/src/redmine/lib/redmine/thumbnail.rb:21:in `<top (required)>'
redmine    | /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
redmine    | /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
redmine    | /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
redmine    | /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
redmine    | /usr/src/redmine/lib/redmine.rb:47:in `<top (required)>'
redmine    | /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
redmine    | /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
redmine    | /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
redmine    | /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
redmine    | /usr/src/redmine/config/initializers/30-redmine.rb:6:in `<top (required)>'
redmine    | /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `load'
redmine    | /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `block in load'
redmine    | /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
redmine    | /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `load'
redmine    | /usr/local/bundle/gems/railties-5.2.2/lib/rails/engine.rb:657:in `block in load_config_initializer'
redmine    | /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/notifications.rb:170:in `instrument'
redmine    | /usr/local/bundle/gems/railties-5.2.2/lib/rails/engine.rb:656:in `load_config_initializer'
redmine    | /usr/local/bundle/gems/railties-5.2.2/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
redmine    | /usr/local/bundle/gems/railties-5.2.2/lib/rails/engine.rb:613:in `each'
redmine    | /usr/local/bundle/gems/railties-5.2.2/lib/rails/engine.rb:613:in `block in <class:Engine>'
redmine    | /usr/local/bundle/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
redmine    | /usr/local/bundle/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
redmine    | /usr/local/bundle/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
redmine    | /usr/local/bundle/gems/railties-5.2.2/lib/rails/initializable.rb:50:in `each'
redmine    | /usr/local/bundle/gems/railties-5.2.2/lib/rails/initializable.rb:50:in `tsort_each_child'
redmine    | /usr/local/bundle/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
redmine    | /usr/local/bundle/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
redmine    | /usr/src/redmine/config/environment.rb:14:in `<top (required)>'
redmine    | /usr/local/bundle/gems/railties-5.2.2/lib/rails/application.rb:337:in `require'
redmine    | /usr/local/bundle/gems/railties-5.2.2/lib/rails/application.rb:337:in `require_environment!'
redmine    | /usr/local/bundle/gems/railties-5.2.2/lib/rails/application.rb:520:in `block in run_tasks_blocks'
redmine    | Tasks: TOP => db:migrate => db:load_config => environment
redmine    | (See full trace by running task with --trace)
redmine exited with code 1

**Comment by wglambert** [comment]
I think the issue is with the yml formatting `SyntaxError: (): mapping values are not allowed in this context at line 4 column 20`

**Comment by heymis** [comment]
Thanks, yml formatting is wrong and I solved this issue via steps:

image: redmine:4.0.1

1. Start up redmine and log in container
```
docker exec -ti <redmine name> bash
```

2. Copy this example as configuration.yml
/usr/src/redmine/config/configuration.yml.example

3. Add Gmail setting
```
default:
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      enable_starttls_auto: true
      address: smtp.gmail.com
      port: 587
      domain: example.net
      authentication: :login
      user_name: your-account@gmail.com
      password: your-pwd
```

4.  Add volumes for linking this configuration.yml
```
volumes:
       - /data/redmine-config/configuration.yml:/usr/src/redmine/config/configuration.yml:ro
```

5. Change account access for less secure apps
https://support.google.com/accounts/answer/6010255?authuser=2&hl=en

6. Login in Redmine, modify email in "my account" and go to administration > Settings > Email notification  press "Send a test email".
