### ISSUE TITLE
sub-uri

### ISSUE THREAD

**Issue by sudharshanjj** [docker-library/redmine#157]
RedmineApp::Application.routes.default_scope = { :path => '/redmine', :shallow_path => '/redmine' }

Is creating error

RedmineApp::Application.**routes** is no more available in latest version

**Comment by wglambert** [comment]
On the [redmine.org wiki](http://www.redmine.org/projects/redmine/wiki/HowTo_Install_Redmine_on_subdirectory_(sub-URI)_on_Apache) for installing on a sub-URI it looks like you use `Redmine::Utils::relative_url_root = "/redmine" `

**Comment by sudharshanjj** [comment]
I was did the same

Nginx Proxy
```
  location /tracking/ {
       proxy_pass http://xx.xx.xx.xx:8080/ ;
  }
```
environment.rb
```
Rails.application.initialize!
Redmine::Utils::relative_url_root = "/tracking"
```

HTML at browser
```
<script src="**/tracking**/javascripts/application.js?1550767427"></script>
<li><a class="projects" href="**/projects**">Projects</a></li>
```
![Capture](https://user-images.githubusercontent.com/25363114/54330828-3fde6680-463d-11e9-92a5-1f19979fd348.PNG)

through css, js links properly the link for other pages are not modified

**Comment by tianon** [comment]
According to upstream's official documentation, that's still the recommended method for changing this: https://www.redmine.org/projects/redmine/wiki/HowTo_Install_Redmine_in_a_sub-URI

I'm afraid there's really not much more we can do other than suggest trying a Redmine-specific support forum for further help figuring out why that doesn't work.
