### ISSUE TITLE
How to change default 3000 port?

### ISSUE THREAD

**Issue by cloud-rocket** [docker-library/redmine#16]
Can you provide an instructions how to change the default port to 80?

Thanks

**Comment by belak** [comment]
Normally you would just bind the port differently or use a proxy container. For instance, something like `docker run -p 80:3000` would bind port 3000 of the container to port 80 of the host box.

I personally recommend running something like https://github.com/jwilder/nginx-proxy which will let you run multiple http services on one docker host.
