### ISSUE TITLE
Allow overriding isLikelyRedmine

### ISSUE THREAD

**Issue by Silex** [docker-library/redmine#167]
Hello,

My goal is to have a command like this:

`gem install mailcatcher && mailcatcher --ip 0.0.0.0 && passenger start ...`

But because of https://github.com/docker-library/redmine/blob/master/docker-entrypoint.sh#L29 and https://github.com/docker-library/redmine/blob/master/docker-entrypoint.sh#L48 it does not work.

I should be able to either set `isLikelyRedmine` upfront in the ENV or put the block at line 48 in some `init()` function so I could call it manually when I use "unredmine-like" commands.

**Comment by yosifkit** [comment]
Assuming you want the setup from the entrypoint, you should be able to get it with something like the following in a compose yaml (untested):

```yaml
command: sh -c 'gem install mailcatcher && mailcatcher --ip 0.0.0.0 && docker-entrypoint.sh passenger start ...'
# entrypoint:  should work the same
```

**Comment by Silex** [comment]
@yosifkit: no, that does not work because it does not run the block at https://github.com/docker-library/redmine/blob/master/docker-entrypoint.sh#L48 because `isLikelyRedmine` is false because the command is `sh` and not one of rake/rails/passenger.

What you suggest is exactly what I tried and why I'm creating this issue.

**Comment by Silex** [comment]
@tianon: ah, thanks I missed that! indeed the suggestion should work. Thanks :+1:
