### ISSUE TITLE
Accesses redmine.org from help

### ISSUE THREAD

**Issue by eccles** [docker-library/redmine#17]
Hi

I installed redmine from docker using this link https://hub.docker.com/_/redmine/
I used port 3000 to access from localhost and everything seems ok. I clicked on the help button and the link changed to redmine.org. I did not notice this but on returning to the home page I see that I now have access to the redmine project itself without any authentication.

I would have expected that clicking on any link in the dockerised instance would always leave me in my own redmine instance and not redmine.org.
1. Login to http://localhost:3000
2. Click on 'Help' - notice the link changes to redmine.org
3. Click on home - project redmine details are shown instead of my own localhost instance

**Comment by yosifkit** [comment]
I believe the help link has always linked to the organization's website, you would need to hit back rather than the home link to get back to your local instance.

**Comment by tianon** [comment]
Indeed -- there's nothing related to this behavior that we modify in our
Dockerization, so this is Redmine working as designed AFAICT.
