### ISSUE TITLE
ImageMagick PDF supporting for 4.1

### ISSUE THREAD

**Issue by liminspace** [docker-library/redmine#188]
I would be great to make `ImageMagick PDF support available (optional)` enabled.

**Comment by tianon** [comment]
The image already includes ImageMagick: https://github.com/docker-library/redmine/blob/a710473af3bf2bea63d2d1d8e0a84facaa7b0b5d/Dockerfile-debian.template#L22

From what I can tell, it used to be required to install `rmagick` (referenced by https://www.redmine.org/projects/redmine/wiki/RedmineInstall#Optional-dependencies, for example), but the project appears to be using `mini_magick` now instead ("Feature #30492: Replace RMagick with MiniMagick" -- https://www.redmine.org/issues/30492).

That being said, I've confirmed that `/admin/info` does contain the message/warning you describe, and PDF previewing does not work, and there is nothing useful or even out of the ordinary in the logs to give us clues as to why generating a preview did not work.

**Comment by tianon** [comment]
According to the code in https://github.com/redmine/redmine/blob/4082069c75223009b222f1e9d45a608fad6ae87c/lib/redmine/thumbnail.rb, we should be getting an error message if the PDF thumbnail conversion fails. :confused:

**Comment by tianon** [comment]
Got it, we're missing `ghostscript`: https://github.com/docker-library/redmine/pull/189 :+1:
