### ISSUE TITLE
Change the default password of the database when first run this image

### ISSUE THREAD

**Issue by huanying061803** [docker-library/redmine#19]
This image's default database password is "secret", but my mysql database's password is not. so ,the question is how should I do to run(docker run ) it with my own database ? I don't want to change my database password yet. Thanks!

**Comment by belak** [comment]
You can use the following environment variables:

```
MYSQL_ENV_MYSQL_USER (defaults to 'root')
MYSQL_ENV_MYSQL_PASSWORD
MYSQL_ENV_MYSQL_DATABASE (defaults to 'redmine')
```

Or if you're using postgres:
```
POSTGRES_ENV_POSTGRES_USER (defaults to postgres)
POSTGRES_ENV_POSTGRES_PASSWORD
POSTGRES_ENV_POSTGRES_DB (defaults to $username, which I assume means 'redmine')
```

**Comment by huanying061803** [comment]
bad news, these three variables can't make it work ,I 'cat'ed the entrypoint file(look at the picture following),it seems like also need a environment variables named "MYSQL_PORT_3306_TCP" .
![qq 20160509180915](https://cloud.githubusercontent.com/assets/3530348/15110041/3873b86e-1611-11e6-9302-5e29549f855b.png)
and i tried this command :
-------------------------------------------------------------------------
docker run -d \
--name redmine \
--restart=always \
-p 3000:3000 \
--link mysql:mysql \
-e MYSQL_PORT_3306_TCP='true' \
-e MYSQL_ENV_MYSQL_PASSWORD=root \
redmine:latest
-------------------------------------------------------------------------
it  works , but i don't know why .

**Comment by belak** [comment]
I think `MYSQL_PORT_3306_TCP` should be set automatically when you link a container called mysql which exports port 3306, but I could be wrong. There are all sorts of strange envars set by docker when linking containers.
