### ISSUE TITLE
Errno::Econnreset: connection reset by peer @ io_fillbuf - fd:16

### ISSUE THREAD

**Issue by karippery** [docker-library/redmine#193]
Hello all,

I need a help from you. my task is dockerized my current redmine.
almost 2 week I am working on this task.
I copied public folder from host redmine to docker container redmine/public
I copied all plugins and installed successfully 
**but problem is image,my theme background image, wiki image is not disply.**

I think my docker redmine is not find path to image.

any one know how to display image?

I will explain what step i do so far.

    docker network create --driver bridge redmine_network
    docker volume create postgres-data
    docker volume create redmine-data
    
    docker container run -d                         \ 
          --name postgres                           \ 
          --network redmine_network                 \ 
          -v postgres-data:/var/lib/postgresql/data \ 
          --restart always                          \ 
          -e POSTGRES_PASSWORD='password'             \ 
          -e POSTGRES_DB='redmine'                  \ 
          postgres:latest
    
    
    
    docker container run -d                         \ 
        --name redmine                              \ 
        --network redmine_network                   \ 
        -p 80:3000                                  \ 
        --restart always                            \ 
        -v redmine-data:/usr/src/redmine/files      \ 
        -e REDMINE_DB_POSTGRES='postgres'           \ 
        -e REDMINE_DB_DATABASE='redmine'            \ 
        -e REDMINE_DB_PASSWORD='password'           \ 
        redmine:latest

inside the container i install some package and gem for my plugins 

    docker exec -it redmine bash
    
    apt update 
    apt install build-essential libpq-dev pkg-config libmagickwand-dev ruby ruby-dev
    bundle install --no-deployment
    gem install will_paginate 
    gem install jenkins_api_client
    gem install activesupport -v 4.2.8
    gem install  haml-rails -v 1.0
    gem install deface -v 1.0.2
    gem install brakeman -v 4.8.0
    bundle updates

docker redmine log file 

    Resolving dependencies...
    The Gemfile's dependencies are satisfied
    [2020-03-17 16:31:41] INFO  WEBrick 1.3.1
    [2020-03-17 16:31:41] INFO  ruby 2.4.4 (2018-03-28) [x86_64-linux]
    [2020-03-17 16:31:41] INFO  WEBrick::HTTPServer#start: pid=1 port=3000
    [2020-03-17 16:32:03] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:16 
    	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `eof?'
    	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `run'
    	/usr/local/lib/ruby/2.4.0/webrick/server.rb:308:in `block in start_thread'
    [2020-03-17 16:32:03] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:14 
    	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `eof?'
    	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `run'
    	/usr/local/lib/ruby/2.4.0/webrick/server.rb:308:in `block in start_thread'
    [2020-03-17 16:32:08] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:19 
    	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `eof?'
    	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `run'
    	/usr/local/lib/ruby/2.4.0/webrick/server.rb:308:in `block in start_thread'
    [2020-03-17 16:32:08] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:13 
    	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `eof?'
    	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `run'
    	/usr/local/lib/ruby/2.4.0/webrick/server.rb:308:in `block in start_thread'
    [2020-03-17 16:32:08] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:18 
    	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `eof?'
    	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `run'
    	/usr/local/lib/ruby/2.4.0/webrick/server.rb:308:in `block in start_thread'
    [2020-03-17 16:32:09] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:16 
    	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `eof?'
    	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `run'
    	/usr/local/lib/ruby/2.4.0/webrick/server.rb:308:in `block in start_thread'
    [2020-03-17 16:32:09] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:14 
    	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `eof?'
    	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `run'
    	/usr/local/lib/ruby/2.4.0/webrick/server.rb:308:in `block in start_thread'

anyone could explain how to clear this error.. please

**Comment by wglambert** [comment]
I'm not able to reproduce the issue, from your commands I can login and do everything normally

```dockerfile
FROM redmine
RUN apt update && \
apt install -y build-essential libpq-dev pkg-config libmagickwand-dev ruby ruby-dev
RUN bundle install --no-deployment
RUN gem install will_paginate 
RUN gem install jenkins_api_client 
RUN gem install activesupport -v 4.2.8 
RUN gem install  haml-rails -v 1.0 
RUN gem install deface -v 1.0.2 
RUN gem install brakeman -v 4.8.0 
RUN bundle update
```

```console
$ docker build . -t redmine:testSending build context to Docker daemon  38.26MB
Step 1/10 : FROM redmine
 ---> da07e8d1fa63
Step 2/10 : RUN apt update && apt install -y build-essential libpq-dev pkg-config libmagickwand-dev ruby ruby-dev
 ---> Using cache
 ---> b1ef9d2961f5
Step 3/10 : RUN bundle install --no-deployment
 ---> Using cache
 ---> 2fe1ea185737
Step 4/10 : RUN gem install will_paginate
 ---> Using cache
 ---> 6915aaa8502f
Step 5/10 : RUN gem install jenkins_api_client
 ---> Using cache
 ---> f503fb63a920
Step 6/10 : RUN gem install activesupport -v 4.2.8
 ---> Using cache
 ---> 4d17ca8a96c6
Step 7/10 : RUN gem install  haml-rails -v 1.0
 ---> Using cache
 ---> d7f4ba6e6c94
Step 8/10 : RUN gem install deface -v 1.0.2
 ---> Using cache
 ---> 83b4096c8618
Step 9/10 : RUN gem install brakeman -v 4.8.0
 ---> Using cache
 ---> 5c78f77cd5b7
Step 10/10 : RUN bundle update
 ---> Using cache
 ---> f00e0c9c83e9
Successfully built f00e0c9c83e9
Successfully tagged redmine:test
```

```console
$ docker network create --driver bridge redmine_network && \
> docker volume create postgres-data && \
> docker volume create redmine-data
255aa75f104dcdf41cee4fc87c07f67446ea7359efa4895b5fb0a6de20598840
postgres-data
redmine-data

$ docker run -d --name postgres --network redmine_network -v postgres-data:/var/lib/postgresql/data -e POSTGRES_PASSWORD=password -e POSTGRES_DB=redmine postgres
aa245621ad80d820836c7a659b28ebc48469cbafac7a7aecf54610a230e8815a

$ docker run -d --name redmine --network redmine_network -p 80:3000 -v redmine-data:/usr/src/redmine/files -e REDMINE_DB_POSTGRES='postgres' -e REDMINE_DB_DATABASE='redmine' -e REDMINE_DB_PASSWORD='password' redmine:test
66be95597b4624b9a15629355c691ce0874778361fa03d26b087131f5e1c8a21

$ docker logs -f redmine
[. . .]
I, [2020-03-18T17:45:30.185633 #28]  INFO -- : Migrating to AddUniqueIdToImportItems (20190510070108)
== 20190510070108 AddUniqueIdToImportItems: migrating =========================
-- change_table(:import_items)
   -> 0.0043s
== 20190510070108 AddUniqueIdToImportItems: migrated (0.0044s) ================

I, [2020-03-18T17:45:30.195533 #28]  INFO -- : Migrating to ChangeRolesNameLimit (20190620135549)
== 20190620135549 ChangeRolesNameLimit: migrating =============================
-- change_column(:roles, :name, :string, {:limit=>255, :default=>""})
   -> 0.0021s
== 20190620135549 ChangeRolesNameLimit: migrated (0.0022s) ====================

[2020-03-18 17:45:34] INFO  WEBrick 1.4.2
[2020-03-18 17:45:34] INFO  ruby 2.6.5 (2019-10-01) [x86_64-linux]
[2020-03-18 17:45:34] INFO  WEBrick::HTTPServer#start: pid=1 port=3000
172.18.0.1 - - [18/Mar/2020:17:46:25 UTC] "GET / HTTP/1.1" 200 4739
- -> /
172.18.0.1 - - [18/Mar/2020:17:47:44 UTC] "GET /login HTTP/1.1" 200 5172
http://ip172-18-0-30-bpp5knfnctv000aagfl0-80.direct.labs.play-with-docker.com/ -> /login
172.18.0.1 - - [18/Mar/2020:17:48:04 UTC] "POST /login HTTP/1.1" 302 144
http://ip172-18-0-30-bpp5knfnctv000aagfl0-80.direct.labs.play-with-docker.com/login -> /login
172.18.0.1 - - [18/Mar/2020:17:48:04 UTC] "GET / HTTP/1.1" 302 155
http://ip172-18-0-30-bpp5knfnctv000aagfl0-80.direct.labs.play-with-docker.com/login -> /
172.18.0.1 - - [18/Mar/2020:17:48:04 UTC] "GET /my/password HTTP/1.1" 200 5722
http://ip172-18-0-30-bpp5knfnctv000aagfl0-80.direct.labs.play-with-docker.com/login -> /my/password
172.18.0.1 - - [18/Mar/2020:17:48:04 UTC] "GET /images/exclamation.png HTTP/1.1" 200 648
http://ip172-18-0-30-bpp5knfnctv000aagfl0-80.direct.labs.play-with-docker.com/stylesheets/application.css?1576844386 -> /images/exclamation.png
172.18.0.1 - - [18/Mar/2020:17:48:14 UTC] "POST /my/password HTTP/1.1" 200 5962
http://ip172-18-0-30-bpp5knfnctv000aagfl0-80.direct.labs.play-with-docker.com/my/password -> /my/password
172.18.0.1 - - [18/Mar/2020:17:48:26 UTC] "POST /my/password HTTP/1.1" 302 154
http://ip172-18-0-30-bpp5knfnctv000aagfl0-80.direct.labs.play-with-docker.com/my/password -> /my/password
172.18.0.1 - - [18/Mar/2020:17:48:27 UTC] "GET /my/account HTTP/1.1" 200 21270
http://ip172-18-0-30-bpp5knfnctv000aagfl0-80.direct.labs.play-with-docker.com/my/password -> /my/account
172.18.0.1 - - [18/Mar/2020:17:48:27 UTC] "GET /images/true.png HTTP/1.1" 200 248
http://ip172-18-0-30-bpp5knfnctv000aagfl0-80.direct.labs.play-with-docker.com/stylesheets/application.css?1576844386 -> /images/true.png
172.18.0.1 - - [18/Mar/2020:17:48:27 UTC] "GET /images/email_add.png HTTP/1.1" 200 761
http://ip172-18-0-30-bpp5knfnctv000aagfl0-80.direct.labs.play-with-docker.com/stylesheets/application.css?1576844386 -> /images/email_add.png
172.18.0.1 - - [18/Mar/2020:17:48:27 UTC] "GET /images/textfield_key.png HTTP/1.1" 200 455
http://ip172-18-0-30-bpp5knfnctv000aagfl0-80.direct.labs.play-with-docker.com/stylesheets/application.css?1576844386 -> /images/textfield_key.png
172.18.0.1 - - [18/Mar/2020:17:48:42 UTC] "GET /projects HTTP/1.1" 200 13168
http://ip172-18-0-30-bpp5knfnctv000aagfl0-80.direct.labs.play-with-docker.com/my/account -> /projects
172.18.0.1 - - [18/Mar/2020:17:48:42 UTC] "GET /images/changeset.png HTTP/1.1" 200 459
http://ip172-18-0-30-bpp5knfnctv000aagfl0-80.direct.labs.play-with-docker.com/stylesheets/application.css?1576844386 -> /images/changeset.png
172.18.0.1 - - [18/Mar/2020:17:48:42 UTC] "GET /images/add.png HTTP/1.1" 200 680
http://ip172-18-0-30-bpp5knfnctv000aagfl0-80.direct.labs.play-with-docker.com/stylesheets/application.css?1576844386 -> /images/add.png
172.18.0.1 - - [18/Mar/2020:17:48:42 UTC] "GET /images/arrow_right.png HTTP/1.1" 200 287
http://ip172-18-0-30-bpp5knfnctv000aagfl0-80.direct.labs.play-with-docker.com/stylesheets/application.css?1576844386 -> /images/arrow_right.png
172.18.0.1 - - [18/Mar/2020:17:48:42 UTC] "GET /images/bullet_toggle_plus.png HTTP/1.1" 200 136
http://ip172-18-0-30-bpp5knfnctv000aagfl0-80.direct.labs.play-with-docker.com/stylesheets/application.css?1576844386 -> /images/bullet_toggle_plus.png
172.18.0.1 - - [18/Mar/2020:17:48:42 UTC] "GET /images/toggle_check.png HTTP/1.1" 200 262
http://ip172-18-0-30-bpp5knfnctv000aagfl0-80.direct.labs.play-with-docker.com/stylesheets/application.css?1576844386 -> /images/toggle_check.png
172.18.0.1 - - [18/Mar/2020:17:48:42 UTC] "GET /images/reload.png HTTP/1.1" 200 549
http://ip172-18-0-30-bpp5knfnctv000aagfl0-80.direct.labs.play-with-docker.com/stylesheets/application.css?1576844386 -> /images/reload.png
172.18.0.1 - - [18/Mar/2020:17:48:42 UTC] "GET /images/save.png HTTP/1.1" 200 440
172.18.0.1 - - [18/Mar/2020:17:48:42 UTC] "GET /images/user.png HTTP/1.1" 200 669
http://ip172-18-0-30-bpp5knfnctv000aagfl0-80.direct.labs.play-with-docker.com/stylesheets/application.css?1576844386 -> /images/user.png
http://ip172-18-0-30-bpp5knfnctv000aagfl0-80.direct.labs.play-with-docker.com/stylesheets/application.css?1576844386 -> /images/save.png
172.18.0.1 - - [18/Mar/2020:17:48:43 UTC] "GET /images/feed.png HTTP/1.1" 200 427
http://ip172-18-0-30-bpp5knfnctv000aagfl0-80.direct.labs.play-with-docker.com/stylesheets/application.css?1576844386 -> /images/feed.png
```

It seems your stackoverflow post is still unanswered https://stackoverflow.com/questions/60726586/host-redmine-to-docker-redmine-error-errnoeconnreset-connection-reset-by-peer

This one might be relevant https://stackoverflow.com/questions/55835869/econnreset-error-when-accessing-ruby-application-which-runs-in-webrick
This seems like the same issue, but unanswered https://talk.jekyllrb.com/t/strange-webrick-exception/2538

**Comment by karippery** [comment]
I want to make docker redmine same like my host redmine.
i can explain what i did so far.
1.  create docker containers for redmine 3.4.4 and postgresql:latest with network and volume for each container 
https://medium.com/@gurayy/setting-up-redmine-with-docker-be110387ba1c 
<img width="673" alt="docker redmine wiki" src="https://user-images.githubusercontent.com/33422429/76993571-52286a00-694d-11ea-81ee-0e7f279951c6.PNG">
<img width="681" alt="docker redmine" src="https://user-images.githubusercontent.com/33422429/76993574-52c10080-694d-11ea-9487-82cb010ca0d7.PNG">
<img width="947" alt="docker redmine info" src="https://user-images.githubusercontent.com/33422429/76993578-53599700-694d-11ea-9c25-ecbca7c4238b.PNG">

[redmine logs.txt](https://github.com/docker-library/redmine/files/4350639/redmine.logs.txt)

2. install package and gem in redmine container 
3. copy **/public**  folder to docker  redmine:/usr/src/redmine
4 copy **all plugins**  to  docker  redmine:/usr/src/redmine/plugins
5. install plugins 
`   bundle exec rake redmine:plugins NAME=readme_at_repositories RAILS_ENV=production`
7  docker container restart redmine
8.  check everything work fine 
9.  make a pg_dump from my host machine 
`    /usr/bin/pg_dump -U postgres -h localhost -W -F -T --file=/tmp/redminedata.sqlc projectportal`
10.  enter to my postgresql container and restore my database 
      pg_restore -c -U postgres -h postgres -d projectportal /tmp/redminedata.sqlc
11. restart redmine container and I check again redmine in browser

when I check my redmine .png and .jpg  files not working (not showing)
all data are migrated but image are missing and my theme background image .

**Comment by karippery** [comment]
I found the problem but I don`t know how to solve this. please anyone help me 
file from host (\redmine\db\schema.rb) missmatch with \db\schema.rb file in docker container.

i attached files here docker and host. I hope this is the reason for this error

[schema_host.rb.txt](https://github.com/docker-library/redmine/files/4370606/schema_host.rb.txt)


[schema_docker.rb.txt](https://github.com/docker-library/redmine/files/4370602/schema_docker.rb.txt)

<img width="528" alt="dockerpng" src="https://user-images.githubusercontent.com/33422429/77339018-76a88b80-6d2b-11ea-8b35-e0f3bdda7214.PNG">

**Comment by karippery** [comment]
i found the solution.. it so simple just cop your /var/lib/redmine/files to /redmine/files folder in docker container.
