### ISSUE TITLE
docker: Error response from daemon: network some-network not found

### ISSUE THREAD

**Issue by KES777** [docker-library/redmine#194]
This is not described [here](https://hub.docker.com/_/redmine), but should I run next command:

     docker network create --driver bridge some-network

before 

     docker run -d --name some-postgres --network some-network -e POSTGRES_PASSWORD=secret -e POSTGRES_USER=redmine postgres
     docker run -d --name some-redmine --network some-network -e REDMINE_DB_POSTGRES=some-postgres -e REDMINE_DB_USERNAME=redmine -e REDMINE_DB_PASSWORD=secret redmine

**Comment by wglambert** [comment]
I can't reproduce
```console
$ docker network create --driver bridge some-network
b9a9ec2d012eecd75d0c6a04a35d92ccb2ec53c735047c492b963dadd8fa2029

$ docker run -d --name some-postgres --network some-network -e POSTGRES_PASSWORD=secret -e POSTGRES_USER=redmine postgres
e424d9734e8e6218e0dfa6517593c1670518f63b3644d73239e2c1b6ea139615

$  docker run -d --name some-redmine --network some-network -e REDMINE_DB_POSTGRES=some-postgres -e REDMINE_DB_USERNAME=redmine -e REDMINE_DB_PASSWORD=secret redmine
8dde777d4714232be98467bff06b328694e37d0f5cb1f0e01ad506715d93abb9
```

What's the output of `docker network ls`?
```console
$ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
473a473df3fa        bridge              bridge              local
1f4ceee9a8ec        host                host                local
4faffd137dcf        none                null                local
b9a9ec2d012e        some-network        bridge              local
```

And what's your `docker version`

**Comment by yosifkit** [comment]
Yes, the `some-network` was added instead of using `--link` (which is deprecated) so that docker would do DNS for the names of other containers in the same network (which is not available on the `default` docker network). The name of the network is irrelevant so long as they are all on the same one and that you set `--name` for any containers that you want to be able to look up through DNS by that name (from other containers in that network).  So the `--name some-postgres` on the postgres contianer needs to match the value passed to redmine: `-e REDMINE_DB_POSTGRES=some-postgres`

Also, `--driver bridge` is the default, so it could be left off.

**Comment by KES777** [comment]
I am sorry. I was not sharp when openning issue.

When I run:
```
docker run -d --name some-postgres --network some-network -e POSTGRES_PASSWORD=secret -e POSTGRES_USER=redmine postgres
```
I got the error.

error occur, because the network is not know to docker yet.
In this ticket I suggest to add next command to documentation.
```
 docker network create --driver bridge some-network
```


@wglambert 
Yes, you can not reproduce, because you create network [here](https://github.com/docker-library/redmine/issues/194#issuecomment-603899985)
```
$ docker network create --driver bridge some-network
b9a9ec2d012eecd75d0c6a04a35d92ccb2ec53c735047c492b963dadd8fa2029
```

Try without network creation ;-) as documented:
![_3](https://user-images.githubusercontent.com/799021/77662529-a7cfc880-6f84-11ea-8ebe-6d7a02391ea5.jpg)

**Comment by yosifkit** [comment]
We left the `docker network create` out on purpose.  It is a common enough docker command that we didn't want to add it to the documentation of every individual image.

**Comment by KES777** [comment]
ah, ok. I am not docker user, so I spent some time to resolve problem.

**Comment by YetiSPb** [comment]
It would be very funny if it weren't sad. The instruction from the official site cannot be executed.

root@95-163-242-90:~# docker run -d --name some-redmine redmine
Unable to find image 'redmine:latest' locally
latest: Pulling from library/redmine
a603fa5e3b41: Pull complete
824cc1987b4c: Pull complete
36e7129cddea: Pull complete
3ff5bad3b104: Pull complete
58cfadccac79: Pull complete
8f1e1ac5ca7a: Pull complete
a449a177b070: Pull complete
be1342d9157e: Pull complete
f88dbab0bc9d: Pull complete
4a91b7ec0fb8: Pull complete
f68a7426ee7b: Pull complete
5b7feed32fc2: Pull complete
Digest: sha256:e6ba18e26e7bd45228e8f55f5ff078ae7a0f1c00e234d5be605ed464aa8c58d8
Status: Downloaded newer image for redmine:latest
ddd90d222281410124b64601abab71d5d1c360a7d19bbfbff4b9fd929776691a
root@95-163-242-90:~# docker run -d --name some-mysql --network some-network -e MYSQL_USER=redmine -e MYSQL_PASSWORD=secret -e MYSQL_DATABASE=redmine -e MYSQL_RANDOM_ROOT_PASSWORD=1 mysql:5.7
Unable to find image 'mysql:5.7' locally
5.7: Pulling from library/mysql
9a0b9cd2dfe6: Pull complete
c637408ee7df: Pull complete
4c517093c276: Pull complete
301cc7d68c2a: Pull complete
17ca9bf9231a: Pull complete
9ae101e5c786: Pull complete
04baa409344e: Pull complete
f0b6015bf853: Pull complete
6005bb052ef8: Pull complete
99f303d57050: Pull complete
307a9a80c1df: Pull complete
Digest: sha256:0e3435e72c493aec752d8274379b1eac4d634f47a7781a7a92b8636fa1dc94c1
Status: Downloaded newer image for mysql:5.7
5437c72d029d97b9c9b6e08fe1bc83f827108060ee2c3569fa9a05d9f7996977
docker: Error response from daemon: network some-network not found.
root@95-163-242-90:~# docker run -d --name some-redmine --network some-network -e REDMINE_DB_MYSQL=some-mysql -e REDMINE_DB_USERNAME=redmine -e REDMINE_DB_PASSWORD=secret redmine
docker: Error response from daemon: Conflict. The container name "/some-redmine" is already in use by container "ddd90d222281410124b64601abab71d5d1c360a7d19bbfbff4b9fd929776691a". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.

**Comment by don-rumata** [comment]
My soltion:

```
docker compose up -d --force-recreate
```
