### ISSUE TITLE
Redmine service ready time is too long

### ISSUE THREAD

**Issue by chenliu1993** [docker-library/redmine#197]
Hi all, I am running redmine:latest with port-mapping. And I tried to verify if the service is ready by `curl localhost:3000`. 
But the service took almost 9 minutes to start. I notice that 
`ruby /usr/local/bundle/bin/rake db:migrate` took almost 4 minutes and after the log
`migrated` shows,I still have to wait for another two minutes to make curl succeed (which in this period the`ruby bin/rails server -b 0.0.0.0` is running).
Could anyone have ideas about this issue?

I am using 2 CPU and 4 GB

Thank you.

**Comment by wglambert** [comment]
What's your host environment, is there a lot of data it's loading?

Does it exhibit this on a new container with no volume mapping?

**Comment by chenliu1993** [comment]
I am running in a Linux VM, and there is no other heavy processes are running. And I am not using a  volume mapping  on this container.

**Comment by chenliu1993** [comment]
I am using 2 CPU and 4 GB VM

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant files or logs for reproducing the issue

Anything special with the hardware, ARM cpu or a slow HDD?

**Comment by chenliu1993** [comment]
Sorry , This may be  because we are not using a normal rootfs on disk and a 9p folder. So closes this.
Thank you for your warm heart.
