### ISSUE TITLE
Update redmine

### ISSUE THREAD

**Issue by rwky** [docker-library/redmine#2]
Redmine, 3.0.5 and 2.6.7 have been released can you please update the packages.

**Comment by yosifkit** [comment]
Thanks for the heads up.  Fixed via https://github.com/docker-library/redmine/commit/b1ee49aa86501363e5832fad93938cf40428c5b7.

**Comment by rwky** [comment]
Thanks :smile: would you mind commenting when you've pushed to docker hub?

**Comment by yosifkit** [comment]
Tis pushed!

**Comment by rwky** [comment]
Thank you!
