### ISSUE TITLE
 Regarding log output with redmine-passenger

### ISSUE THREAD

**Issue by shunta27** [docker-library/redmine#204]
hi,

`redmine:3.4.13-passenger` image
I am running redmine using it, but the container size increases with the following log output.
I want to change the log output to stdout instead of a file. Is there a way?

```bash
$ ps aux
...
redmine    237  0.0  0.0   2384   760 ?        S    21:24   0:00 sh -c tail -f -n 0 "/usr/src/redmine/log/passenger.3000.log"
redmine    240  0.0  0.0   2324   680 ?        S    21:24   0:00 tail -f -n 0 /usr/src/redmine/log/passenger.3000.log
...
```

**Comment by tianon** [comment]
According to https://www.phusionpassenger.com/library/config/standalone/reference/#--log-file-log_file, it looks like this might be possible since Passenger 5.0.29 -- can you try out setting `--env PASSENGER_LOG_FILE=/dev/stdout` and let us know if that works?

(If it does, I think we should probably update the `passenger` variants to include it. :+1:)

**Comment by shunta27** [comment]
Thank you.
When I tried it, nginx fell down this time.
Hmm, what are you doing

```bash
nginx: [emerg] open() "/dev/stdout" failed (13: Permission denied)
Could not start the Nginx engine:
Daemon 'Nginx' failed to start.
```

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant files or logs for reproducing the issue

**Comment by laf0rge** [comment]
The problem persists till today.  One can watch the logs grow to dozens of gigabytes over time.  An official container image should not grow boundless.

**Comment by yosifkit** [comment]
It looks like it is just a permissions problem. This works to redirect it to docker logs:
```console
$ docker run -it --rm --env PASSENGER_LOG_FILE=/dev/stdout --user redmine redmine:passenger
...
[ N 2022-02-05 00:18:46.1351 28/T1 age/Wat/WatchdogMain.cpp:1373 ]: Starting Passenger watchdog...
[ N 2022-02-05 00:18:46.1463 31/T1 age/Cor/CoreMain.cpp:1340 ]: Starting Passenger core...
[ N 2022-02-05 00:18:46.1464 31/T1 age/Cor/CoreMain.cpp:256 ]: Passenger core running in multi-application mode.
[ N 2022-02-05 00:18:46.2328 31/T1 age/Cor/CoreMain.cpp:1015 ]: Passenger core online, PID 31
=============== Phusion Passenger(R) Standalone web server started ===============
PID file: /usr/src/redmine/tmp/pids/server.pid
Log file: /dev/stdout
Environment: production
Accessible via: http://0.0.0.0:3000/

You can stop Phusion Passenger(R) Standalone by pressing Ctrl-C.
Problems? Check https://www.phusionpassenger.com/library/admin/standalone/troubleshooting/
===============================================================================
...
```

---

I think it would be reasonable to add a fix like https://github.com/docker-library/mongo/pull/151 to `chown` if running as `root` and then also add `ENV PASSENGER_LOG_FILE /dev/stdout` to the Dockerfile to be more container native.
