### ISSUE TITLE
Enabling HTTPS should be easy and not require Ruby / rails knowledge?

### ISSUE THREAD

**Issue by MorgusLethe** [docker-library/redmine#207]
I apologize in advance if this is not the appropriate place for this suggestion.

I have successfully setup a redmine container, but I am having difficulties with enabling HTTPS, since I am not familiar with Ruby or rails. In my opinion, "How to enable HTTPS" should be a part of the Docker Hub documentation.

In the spirit of simplicity, I would hope that it could be done just by overriding the default image command from `rails server -b 0.0.0.0` to something else, but so far I have not been successful. The closest I got was through [here](https://madeintandem.com/blog/rails-local-development-https-using-self-signed-ssl-certificate/), where it is suggested to use `rails s -b 'ssl://localhost:3000?key=path/to/file/localhost.key&cert=path/to/file/localhost.crt'`, but this does not work for me; no matter what I put in as the argument to -b, it always prepends "http" and appends ":3000".

I don't want this issue to be too long, but as a user of this redmine image, I am having a lot of trouble with enabling HTTPS, the closest I got was to modify config.ru and create a whole new server instance that does use my certificates. 

What is the simplest answer to "how to enable HTTPS using this docker redmine image?"

**Comment by wglambert** [comment]
These steps should work https://github.com/docker-library/redmine/issues/4#issuecomment-149335151

**Comment by MorgusLethe** [comment]
Thank you, I have already found [those](https://ruby-doc.org/stdlib-2.1.1/libdoc/webrick/rdoc/WEBrick.html#module-WEBrick-label-HTTPS) instructions, but I don't know exactly where to place the configuration, especially not in a way so it doesn't bork up in combination with the default "rails server" command.

If this redmine image uses webrick, and if webrick is perfectly capable of running over https in production for small loads, some information should at least be written somewhere how to enable it. I was unable to help myself with just the webrick documentation.

It's sad because this should be super super simple. Just change one file and modify the command. If anyone knows, please comment!

**Comment by MorgusLethe** [comment]
Okay, I have finally succeeded in enabling HTTPS. To all those fighting to get it working, here is my advice:
* Even though WEBRICK is capable of running over https for small production loads, I have not found exact documentation on what to do to get it working in the context of a docker image
* Don't fight it, just use the Passenger version of this image. Passenger is just an alternative web server, there is nothing you have to change on your application.
* With passenger, you can enable HTTPS just by modifying the CMD in your Dockerfile. Easy and simple, as it should be
* For extra steps and gotchas see #208

**Comment by vjohnk** [comment]
i happen to put https on redmine via aws loadbalancer and via proxy servers
