### ISSUE TITLE
Passenger permission issues with SSL

### ISSUE THREAD

**Issue by MorgusLethe** [docker-library/redmine#208]
I am using the passenger version of this image, and it looks like there are some permission issues when it comes to SSL.
I first noticed it when I had to relax the permissions on my certificate for the container to start, otherwise it could not read the certificate. That worked, and I had fully working https.
Then I wanted to change the port by adding the `--ssl-port 443` to `passenger start`, but now it's saying `bind() to 0.0.0.0:443 failed (13: Permission denied)`.

My Dockerfile:
```
FROM redmine:4.1.0-passenger

#install packages
RUN apt update && apt -y install build-essential ca-certificates ruby-xapian

#import certificates for https
COPY certificates/redmine.pem /usr/local/share/ca-certificates/
COPY certificates/redmine.key /usr/local/share/ca-certificates/
#not sure why permissions need to be relaxed...
RUN chmod -R 777 /usr/local/share/ca-certificates/


CMD ["passenger", "start", "--ssl", "--ssl-certificate", "/usr/local/share/ca-certificates/redmine.pem", "--ssl-certificate-key", "/usr/local/share/ca-certificates/redmine.key", "--ssl-port", "443"]
```

EDIT: Obviously, the thing is not running as root. This is probably a security feature, but perhaps it's a bit too much for a docker container? Could there be privilege de-escalation AFTER passenger starts? This would make it easier to enable HTTPS. Now I have to do some port juggling in my docker-compose file with ports higher than 1024 to make this work, right?

**Comment by MorgusLethe** [comment]
I got it working like I want.
1. In your Dockerfile in the CMD, use --ssl-port higher than 1024 to avoid permission issues. I used 3443. This means your app will probably run on HTTP on port 3000 and HTTPS on port 3443.
2. In your docker compose file (or docker run command), use:
```
ports:
  - "80:3000"
  - "443:3443"
```
3. At this point your app will run over http and https. If you want to redirect http to https, put the line `config.enable_ssl = true` in "config/application.rb". This solution does the redirection on the app level, it could probably also be done on the web-server level (passenger/nginx config), but I haven't found that one yet.

All in all, it was pretty hard to get https working with these redmine images. I'm glad it's over.

**Comment by rafaelteb** [comment]
Hi there! 
Thanks a lot for those infos. I tried to apply them to my situation and all seems to work.
Still I am getting this error when I trie to recieve email through imap:


Currently wanted to setup with cron. But Im constantly getting this error:

**`rake aborted!
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)`**

Any idea what that may be about?
I put my full issue here: https://github.com/docker-library/redmine/issues/232
I am now going to see if sameersbin or bitnami provide an easier solution.
