### ISSUE TITLE
Docker run fail 

### ISSUE THREAD

**Issue by hammersoft** [docker-library/redmine#21]
```
# docker --version 
Docker version 1.11.1, build 5604cbe

```

```
# docker info 
Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 57
 Server Version: 1.11.1
 Storage Driver: devicemapper
  Pool Name: docker-253:0-6443227537-pool
  Pool Blocksize: 65.54 kB
  Base Device Size: 107.4 GB
  Backing Filesystem: ext4
  Data file: /dev/loop0
  Metadata file: /dev/loop1
  Data Space Used: 4.728 GB
  Data Space Total: 107.4 GB
  Data Space Available: 102.6 GB
  Metadata Space Used: 6.197 MB
  Metadata Space Total: 2.147 GB
  Metadata Space Available: 2.141 GB
  Udev Sync Supported: true
  Deferred Removal Enabled: false
  Deferred Deletion Enabled: false
  Deferred Deleted Device Count: 0
  Data loop file: /var/lib/docker/devicemapper/devicemapper/data
  WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
  Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
  Library Version: 1.02.107-RHEL7 (2015-10-14)
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins: 
  Volume: local
  Network: host bridge null
 Kernel Version: 3.10.0-327.4.5.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 15.51 GiB
 Name: some_host_name
 ID: AX6L:Z4WU:ODZY:EQ74:VLQ3:OVU4:Q4TQ:IMFC:4YH7:DTGU:DSP6:543S
 Docker Root Dir: /var/lib/docker
 Debug mode (client): false
 Debug mode (server): false
 Registry: https://index.docker.io/v1/
 WARNING: bridge-nf-call-iptables is disabled
 WARNING: bridge-nf-call-ip6tables is disabled
```

runninng redmine as 
`docker run -d --name redmine --link redmine-mysql:mysql --restart always -v /srv/docker/redmine:/usr/src/redmine/files -v /srv/docker/redmine-plugins:/usr/src/redmine/plugins -p 3000:3000  redmine
`

startup fail`s with 

> Installing mysql2 0.3.21 with native extensions
> 
> Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
> 
> ```
> current directory: /usr/local/bundle/gems/mysql2-0.3.21/ext/mysql2
> ```
> 
> /usr/local/bin/ruby -r ./siteconf20160516-5-1w9hlwb.rb extconf.rb
> checking for ruby/thread.h... **\* extconf.rb failed ***
> Could not create Makefile due to some reason, probably lack of necessary
> libraries and/or headers.  Check the mkmf.log file for more details.  You may
> need configuration options.
> 
> Provided configuration options:
>         --with-opt-dir
>         --without-opt-dir
>         --with-opt-include
>         --without-opt-include=${opt-dir}/include
>         --with-opt-lib
>         --without-opt-lib=${opt-dir}/lib
>         --with-make-prog
>         --without-make-prog
>         --srcdir=.
>         --curdir
>         --ruby=/usr/local/bin/$(RUBY_BASE_NAME)
> /usr/local/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
> You have to install development tools first.
>         from /usr/local/lib/ruby/2.2.0/mkmf.rb:587:in`try_cpp'
>         from /usr/local/lib/ruby/2.2.0/mkmf.rb:1060:in `block in have_header'
>         from /usr/local/lib/ruby/2.2.0/mkmf.rb:911:in`block in checking_for'
>         from /usr/local/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
>         from /usr/local/lib/ruby/2.2.0/mkmf.rb:321:in`open'
>         from /usr/local/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
>         from /usr/local/lib/ruby/2.2.0/mkmf.rb:321:in`open'
>         from /usr/local/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
>         from /usr/local/lib/ruby/2.2.0/mkmf.rb:910:in`checking_for'
>         from /usr/local/lib/ruby/2.2.0/mkmf.rb:1059:in `have_header'
>         from extconf.rb:15:in`<main>'
> 
> To see why this extension failed to compile, please check the mkmf.log which can be found here:
> 
>   /usr/local/bundle/extensions/x86_64-linux/2.2.0-static/mysql2-0.3.21/mkmf.log
> 
> extconf failed, exit code 1
> 
> Gem files will remain installed in /usr/local/bundle/gems/mysql2-0.3.21 for inspection.
> Results logged to /usr/local/bundle/extensions/x86_64-linux/2.2.0-static/mysql2-0.3.21/gem_make.out

**Comment by stefan-hausmann** [comment]
@hammersoft: have you found a solution for that? I have the same problem. When using the redmine:3.2 image from hub.docker.com, it works, but when builing the very same image from github Dockerfile, the error occurs exactly as you've described it

**Comment by yosifkit** [comment]
I see that there is an updated `mysql2` module for `0.3.20` to `0.3.21` on May 8th, but when I run the container, it does not try to automatically install the newer version.  I am unable to reproduce this.

```console
$ docker pull redmine:3.2
3.2: Pulling from library/redmine
Digest: sha256:a558dfe47433e91f3e2b0cbe419ec2c25c372940221273ddc288966e44e94407
Status: Image is up to date for redmine:3.2
$ docker run -d --name mysql -e MYSQL_DATABASE=redmine -e MYSQL_ROOT_PASSWORD=password -d mysql:5.7
$ docker run -it -v redmine:/usr/src/redmine/files -v redmine-plugins:/usr/src/redmine/plugins --name redmine --link mysql:mysql redmine


Resolving dependencies...
Using rake 11.1.2
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.8.4
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile2 2.0.0
Using rack 1.6.4
Using mime-types-data 3.2016.0221
Using arel 6.0.3
Using addressable 2.4.0
Using bundler 1.12.2
Using coderay 1.1.1
Using concurrent-ruby 1.0.2
Using htmlentities 4.3.1
Using thor 0.19.1
Using mimemagic 0.3.1
Using mysql2 0.3.20
Using net-ldap 0.12.1
Using ruby-openid 2.3.0
Using rbpdf-font 1.19.0
Using redcarpet 3.3.4
Using request_store 1.0.5
Using rmagick 2.15.4
Using tzinfo 1.2.2
Using nokogiri 1.6.7.2
Using rack-test 0.6.3
Using mime-types 3.0
Using css_parser 1.3.7
Using sprockets 3.6.0
Using rack-openid 1.4.2
Using rbpdf 1.19.0
Using activesupport 4.2.5.2
Using loofah 2.0.3
Using mail 2.6.4
Using roadie 3.1.1
Using rails-deprecated_sanitizer 1.0.3
Using globalid 0.3.6
Using activemodel 4.2.5.2
Using rails-html-sanitizer 1.0.3
Using rails-dom-testing 1.0.7
Using activejob 4.2.5.2
Using activerecord 4.2.5.2
Using protected_attributes 1.1.3
Using actionview 4.2.5.2
Using actionpack 4.2.5.2
Using actionmailer 4.2.5.2
Using actionpack-action_caching 1.1.1
Using actionpack-xml_parser 1.0.2
Using railties 4.2.5.2
Using sprockets-rails 3.0.4
Using jquery-rails 3.1.4
Using roadie-rails 1.1.1
Using rails 4.2.5.2
Bundle complete! 31 Gemfile dependencies, 55 gems now installed.
Gems in the groups development and test were not installed.
Bundled gems are installed into /usr/local/bundle.
/usr/local/bundle/gems/htmlentities-4.3.1/lib/htmlentities/mappings/expanded.rb:465: warning: duplicated key at line 466 ignored: "inodot"
/usr/local/bundle/gems/htmlentities-4.3.1/lib/htmlentities/mappings/expanded.rb:465: warning: duplicated key at line 466 ignored: "inodot"
== 1 Setup: migrating =========================================================
...
=> Booting WEBrick
=> Rails 4.2.5.2 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[2016-05-24 20:35:03] INFO  WEBrick 1.3.1
[2016-05-24 20:35:03] INFO  ruby 2.2.5 (2016-04-26) [x86_64-linux]
[2016-05-24 20:35:03] INFO  WEBrick::HTTPServer#start: pid=1 port=3000

$ docker diff redmine
C /usr
C /usr/src
C /usr/src/redmine
C /usr/src/redmine/Gemfile.lock
C /usr/src/redmine/config
C /usr/src/redmine/config/initializers
A /usr/src/redmine/config/initializers/secret_token.rb
A /usr/src/redmine/config/database.yml
C /usr/src/redmine/db
A /usr/src/redmine/db/schema.rb
C /usr/src/redmine/log
A /usr/src/redmine/log/production.log
C /usr/src/redmine/tmp
A /usr/src/redmine/tmp/pids
A /usr/src/redmine/tmp/pids/server.pid
C /usr/local
C /usr/local/bundle
C /usr/local/bundle/config
C /usr/local/bundle/bin
C /usr/local/bundle/bin/coderay
C /usr/local/bundle/bin/erubis
C /usr/local/bundle/bin/nokogiri
C /usr/local/bundle/bin/rackup
C /usr/local/bundle/bin/thor
C /usr/local/bundle/bin/rails
C /usr/local/bundle/bin/rake
C /usr/local/bundle/bin/redcarpet
C /usr/local/bundle/bin/sprockets
```

The only difference I see is that I used a named empty volume rather than a local folder like you, but neither folder has anything in them during or after the migrate.  Maybe you have a plugin that is causing the gem to update?  The gem will not be able to update since we only install the build dependencies during the [build](https://github.com/docker-library/redmine/blob/a96891cab13e6e0fac72fc94761a65a5e953c811/3.2/Dockerfile#L56-L76), which is why we preinstall gems for both mysql and postgres since that is much smaller than keeping `gcc` around.

**Comment by hammersoft** [comment]
@stefan-hausmann 
There is no solution for fixing exactly this problem for me. 

Workaround:
0. Stop and remove any existing containers belongs to redmine. (redmine, mysql)
1. Created new empty mysql container
2. Created new empty directories /srv/redmine/{mysql,files,plugins}, specify them in startup commands 
3. Run all containers as described in ticket 
4. All works fine

I think the problem was with some permissions (selinux) with data directories. setenforce=1

**Comment by stefan-hausmann** [comment]
@hammersoft 
Thanks for answering! In the meantime, it works for me as well again.
I think the problem were incorrect file permissions on a host volume that I've mounted into the /usr/source/redmine directory to allow for local plugin development on the host via scp.
After using `chmod redmine:redmine . -R` on all files again, the problem was gone.
