### ISSUE TITLE
fail installing gitlab_hook plugin in a docker image 

### ISSUE THREAD

**Issue by joeshay** [docker-library/redmine#213]
when i do a 'bundle install' in a container redmine:latest env with gitlab_hood plugin from https://github.com/phlegx/redmine_gitlab_hook.git, I got the following errors:

....
Using actionpack-xml_parser 2.0.1
Using roadie-rails 2.1.1
Using rails 5.2.4.2
Installing json 2.3.1 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/bundle/gems/json-2.3.1/ext/json/ext/generator
/usr/local/bin/ruby -I /usr/local/lib/ruby/2.6.0 -r ./siteconf20200815-43-ukroe.rb extconf.rb
creating Makefile

current directory: /usr/local/bundle/gems/json-2.3.1/ext/json/ext/generator
make "DESTDIR=" clean
sh: 1: make: not found

current directory: /usr/local/bundle/gems/json-2.3.1/ext/json/ext/generator
make "DESTDIR="
sh: 1: make: not found

make failed, exit code 127

Gem files will remain installed in /usr/local/bundle/gems/json-2.3.1 for inspection.
Results logged to /usr/local/bundle/extensions/x86_64-linux/2.6.0/json-2.3.1/gem_make.out

An error occurred while installing json (2.3.1), and Bundler cannot continue.
Make sure that `gem install json -v '2.3.1' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  json

any idea what could be possible to cause this?

many thanks

**Comment by ishikawa999** [comment]
I think it works if I run the following command before bundle install.

```
$ apt-get update
$ apt-get install -y gcc g++ make libffi6;
```

Reference: https://github.com/docker-library/redmine/issues/81#issuecomment-335613338

**Comment by joeshay** [comment]
that solved the problem. it turns out that the docker image is lacking the gcc compiler.
Thanks for your help!
