### ISSUE TITLE
MSSQL support is missing

### ISSUE THREAD

**Issue by nmusatov** [docker-library/redmine#215]
Currently image allows usage mysql, postgresql and sqlite, but doesn't allow to use mssql (which is also supported by redmine ootb).
Please add REDMINE_DB_MSSQL env configuration variable and underlying logic to use it with mssql ootb.

**Comment by nmusatov** [comment]
REDMINE_DB_SQLSERVER exists.
This means that documentation should be updated

**Comment by wglambert** [comment]
Ah yeah looks like it was implemented January 2018 https://github.com/docker-library/redmine/pull/100
