### ISSUE TITLE
sub-URIs are not working

### ISSUE THREAD

**Issue by rm4rty** [docker-library/redmine#220]
Following https://www.redmine.org/projects/redmine/wiki/HowTo_Install_Redmine_in_a_sub-URI is not enough to get the redmine docker work under a sub URI. 
Only the main page is well routed.
An environment variable would be great

**Comment by wglambert** [comment]
There was a previous PR suggested for this https://github.com/docker-library/redmine/pull/99

https://github.com/docker-library/redmine/issues/157#issuecomment-474615103
>According to upstream's official documentation, that's still the recommended method for changing this: https://www.redmine.org/projects/redmine/wiki/HowTo_Install_Redmine_in_a_sub-URI

>I'm afraid there's really not much more we can do other than suggest trying a Redmine-specific support forum for further help figuring out why that doesn't work.

**Comment by rm4rty** [comment]
thanks for pointing these posts

**Comment by jouve** [comment]
i'm still using (4.1) https://github.com/docker-library/redmine/pull/99#issuecomment-371627255
