### ISSUE TITLE
Tag 3.2.3 not found in repository docker.io/library/redmine

### ISSUE THREAD

**Issue by stefan-hausmann** [docker-library/redmine#25]
when doing a ```docker pull redmine:3.2.3```, I always get `Tag 3.2.3 not found in repository docker.io/library/redmine`. The PR https://github.com/docker-library/official-images/pull/1827 has been merged in 2 weeks ago - just wondering why the updated image (contains security fixes!) is not available on the hub yet...

Thanks & with best regards
Stefan

**Comment by yosifkit** [comment]
Not sure what happened.  I thought everything was pushed. :confused: It is up now.

**Comment by stefan-hausmann** [comment]
@yosifkit: great, thanks!
