### ISSUE TITLE
Adapter 'postgres'

### ISSUE THREAD

**Issue by sealemar** [docker-library/redmine#26]
Feels like

https://github.com/docker-library/redmine/blob/master/3.2/docker-entrypoint.sh#L22

should be `adapter='postgresql'` instead of `adapter='postgres'`

**Comment by tianon** [comment]
Oh man, indeed it should!  Want to make a PR, or would you prefer one of us
handles it?

**Comment by sealemar** [comment]
I can make a PR :)

**Comment by tianon** [comment]
Woot, will watch for it! :+1:  (be sure to hit the top-level version and
use "./update.sh" or "cp" to propagate the change to all the versions)

**Comment by sealemar** [comment]
got it, will do. Just sent a PR for 3.2, but will redo with your comments

**Comment by sealemar** [comment]
https://github.com/docker-library/redmine/pull/28

let me know if I missed anything
