### ISSUE TITLE
Gitolite support

### ISSUE THREAD

**Issue by lifedanceman** [docker-library/redmine#260]
Hello! Add please gitolite package into docker image which is necessary for git hosting plugin.

**Comment by tianon** [comment]
Is this built-in functionality or an optional plugin that has to be installed separately?

**Comment by lifedanceman** [comment]
This is an optional plugin: http://redmine-git-hosting.io/get_started

**Comment by tianon** [comment]
Ah, that's I figured -- unfortunately, that means we won't be adding `gitolite` by default.  However, it should be reasonably easy to add in your own images, especially since it's available in Debian's repositories.

**Comment by tianon** [comment]
Something like this should do the trick:

```dockerfile
FROM redmine:4.2
RUN apt-get update && apt-get install -y gitolite3
```
