### ISSUE TITLE
`_fix_permissions` in docker-entrypoint.sh is run on every start twice causing problems in installations with lots of files/attachments

### ISSUE THREAD

**Issue by erSitzt** [docker-library/redmine#268]
Hi,

`_fix_permissions` runs two times on every start of the container, when not changing the user.

`chown` is then run only once, but `chmod` for dirs and files is run twice.

This results in 5 runs of `find` over a directory stucture that may contain lots of directories and small files, because the `files` folder where attachments are stored is included.

Our install has files starting from 2014, most issues are generated from email and contain the .eml and all attachments separately ... which results in currently 996388 files

I think this should be changed to run `chown` only on files/dirs that redmine needs to start/run and leave it optional for the `files` folder as this might be very time consuming.

`chmod` for dirs and files should run only once and againt with the option to exclude the `files` folder

There was an old issue suggesting an option to disable the `chown` here #123

**Comment by tianon** [comment]
If we could reduce this to two invocations of `find` total, would that be enough?
(I think we can, but I need to do some more testing :see_no_evil:)

**Comment by erSitzt** [comment]
I think we might not be the only ones with an older redmine Installation and as the files directory is even sometimes a mount or in our case a pvc, the backing filesystem could be NFS/SMB which results in a startup time of 15-30 minutes in our case.
That's for each container if the redmine container is used in a scalable deployment...

So it feels like a bad default to always chown/chmod the files directory. The other directories should be fine.

**Comment by erSitzt** [comment]
And I think this should just be analog to the migrations/plugins env variables.
Default: run chown/chmod on files directory
But add env variable to opt out of this behavior.

I can do a PR for that as well.

**Comment by tianon** [comment]
Thanks for the added detail, @erSitzt (and thanks for being patient with me :bow:)

Would you be willing/able to test the following implementation?

```bash
_fix_permissions() {
	# https://www.redmine.org/projects/redmine/wiki/RedmineInstall#Step-8-File-system-permissions
	local dirs=( config log public/plugin_assets tmp ) sep= args=()
	if [ "$(id -u)" = '0' ]; then
		args+=( ${args[@]:+,} '(' '!' -user redmine -exec chown redmine:redmine '{}' + ')' )

		# https://github.com/docker-library/redmine/issues/268 - scanning "files" might be *really* expensive, so we should skip it if it seems like it's "already correct"
		local filesOwnerMode
		filesOwnerMode="$(stat --format '%U:%a' files)"
		if [ "$files" != 'redmine:755' ]; then
			dirs+=( files )
		fi
	fi
	# directories 755, files 644:
	args+=( ${args[@]:+,} '(' -type d '!' -perm 755 -exec sh -c 'chmod 755 "$@" 2>/dev/null || :' -- '{}' + ')' )
	args+=( ${args[@]:+,} '(' -type f '!' -perm 644 -exec sh -c 'chmod 644 "$@" 2>/dev/null || :' -- '{}' + ')' )
	find "${dirs[@]}" "${args[@]}"
}
```

This should ensure that we only do _anything_ with `files` if the container is started as root *and* `files` (at the top-level only) is not already owned by `redmine` + permissions of 755, and otherwise we do the full recursive scan to handle the migration case somewhat appropriately. :sweat_smile:

**Comment by erSitzt** [comment]
@tianon 
I'll test it and get back to you

**Comment by erSitzt** [comment]
The chmod on the files folder still is the most time consuming i guess...

I added the log output to your snippet
<img width="366" alt="image" src="https://user-images.githubusercontent.com/1625376/178706369-602bf7c7-3d3d-48b3-be12-68868aade10a.png">

**Comment by erSitzt** [comment]
And finally, i can live with either solution you like more :)

**Comment by erSitzt** [comment]
I changed my mind... :) I cant live with it :)
Let it run once an remember that it already ran... better than any bash magic.
