### ISSUE TITLE
Can't find production.log

### ISSUE THREAD

**Issue by ceddup** [docker-library/redmine#271]
Hello,

Running the latest release that is 5.0.2 I can't find production.log.
Logged into the container I checked :
/var/log/redmine
/home/user/redmine/log
/usr/src/redmine/log
They are all empty.
All permissions seam correct.
The host is Ubuntu 20.0.4

I did nothing fancy just a plain regular install using this official docker image. The redmine instance runs fine.
The only specific thing is that this instance has been migrated from a 2.2.3 redmine version.

I mapped the log folder this way :
-v /home/user/redmine_logs:/var/log/redmine
This folder /home/user/redmine_logs on the host is also empty

I googled all I could, I'm puzzled right now. Any help would be greatly appreciated. This might not be the place for this question, I apologize in advance if it's the case.

Thanks

**Comment by wglambert** [comment]
The logs are sent to `stdout` (so that they show in `docker logs`) 
https://github.com/docker-library/redmine/blob/3535e637d03cff07f27044d0032170a92c042c39/5.0/Dockerfile#L58-L59

**Comment by ceddup** [comment]
Oh, ok ! 
I knew my question had to be somehow a bit dumb. Hope it helps someone else after me. 
Thanks a lot anyways !
