### ISSUE TITLE
Why redmine:*.*.*-passenger is not being up-to-date?

### ISSUE THREAD

**Issue by darksidds** [docker-library/redmine#277]
Hi, I'm looking for `redmine:5.0.*-passenger` image, but it looks like the latest supported version is `redmine:4.2.8-passenger`.
Do you have any plans to support `redmine:5.0.*-passenger` image?

**Comment by yosifkit** [comment]
> Given this is a major release, we're finally removing the passenger variant (it hasn't been well supported for quite some time).
>
>\- https://github.com/docker-library/redmine/pull/261

**Comment by darksidds** [comment]
If passenger variant won't be supported any longer, could you recommend anything how to implement this setup https://www.redmine.org/projects/redmine/wiki/HowTo_Install_Redmine_in_a_sub-URI#If-using-Docker-official-image-passenger-variant without passenger image?

**Comment by darksidds** [comment]
Yeap, the problem is solved. Thanks!

Maybe this is not the shortest solution, but it workes! I manually added some configs to docker container (based on image `docker pull redmine:5.0.2-bullseye`)

``` shell
ln -s /usr/src/redmine/public/subfolder /usr/src/redmine/public
chown redmine:redmine /usr/src/redmine/public/subfolder
```

``` conf
# vim /usr/src/redmine/config/environment.rb
RedmineApp::Application.routes.default_scope = "/subfolder"
# Initialize the Rails application
Rails.application.initialize!
```
``` conf
# vim /usr/src/redmine/config/additional_environment.rb
config.relative_url_root = "/subfolder"
```
