### ISSUE TITLE
RequestHeader set X-Forwarded-Proto "https"

### ISSUE THREAD

**Issue by qianzhongxiang** [docker-library/redmine#278]
Hi, I am trying to add `RequestHeader set X-Forwarded-Proto "https"` to Apache, but I can't find the config file of Apache in Redmine container, where is it?

**Comment by yosifkit** [comment]
There is no `apache` in the redmine image, it is just running a rails server directly:

https://github.com/docker-library/redmine/blob/ec6df18000a6b6182f711ff58c3cb4c7ae2582d4/5.0/Dockerfile#L118

You need to set the `X-Forwarded-Proto` configuration in a reverse proxy that is in front of redmine (e.g. a separate container running something like Apache2 or Nginx).

**Comment by qianzhongxiang** [comment]
Thanks a lot, it’s helpful.
