### ISSUE TITLE
Cannot build version 5.0.4 in development mode

### ISSUE THREAD

**Issue by honza2** [docker-library/redmine#285]
During building docker container in development mode appers error:
Your Gemfile lists the gem puma (< 6.0.0) more than once.

**Comment by tianon** [comment]
That's while building _our_ `Dockerfile`, or your own?

(You can see that https://github.com/docker-library/redmine/actions/runs/3920884966 succeeded on all our supported `Dockerfile`s as recently as 3 days ago.)

**Comment by amarynets** [comment]
@tianon I have used versions 5.0.4 and 5, and have the same issue. My container is restarting and shows these messages on repeat. But sometimes it could work properly for a few mins
```
Your Gemfile lists the gem puma (< 6.0.0) more than once.
You should probably keep only one of them.
Remove any duplicate entries and specify the gem only once.
While it's not a problem now, it could cause errors if you change the version of one of them later.
The Gemfile's dependencies are satisfied
=> Booting Puma
=> Rails 6.1.7 application starting in production 
=> Run `bin/rails server --help` for more startup options
```
