### ISSUE TITLE
Ruby 2.7 (is EOL)

### ISSUE THREAD

**Issue by tianon** [docker-library/redmine#289]
We are in a small conundrum - Ruby 2.7 is now EOL (https://www.ruby-lang.org/en/downloads/branches/), but it's the most recent version supported by Redmine 4.2 (https://www.redmine.org/projects/redmine/wiki/redmineinstall).

So, we need to choose between publishing Redmine images of 4.2 on a version of Ruby that the Redmine project does not support, or removing Redmine 4.2 and no longer supporting it. :sweat_smile:

(For the avoidance of doubt, "Removing tags here will remove them from the "Supported" section on the Hub readme (and will prevent us from spending cycles rebuilding them on the official build servers), but the tags will still be available to users who want them.  (See https://github.com/docker-library/official-images#library-definition-files for more detail on this.)")

@marius-balteanu hopefully your offer of being pinged still stands - we could use some "upstream advice" here on which way you'd prefer/suggest we go, if you can spare the time. :sweat_smile:

**Comment by yosifkit** [comment]
> Your Ruby version is 3.0.6, but your Gemfile specified >= 2.4.0, < 2.8.0

We can't update Redmine `4.2.x` to a non-EOL version of Ruby, so I'll drop `4.2` along with the Alpine bump in #294.
