### ISSUE TITLE
the problem of  docker volume  

### ISSUE THREAD

**Issue by cuisongliu** [docker-library/redmine#29]
docker version: 1.12.0-rc3

i'm run commond in terminal : `sudo docker run -d --name redmine -p 8000:3000 -v /mnt/data/redmine:/usr/src/redmine redmine:passenger` 

logs:

warning: missing REDMINE_DB_MYSQL or REDMINE_DB_POSTGRES environment variables
*** Using sqlite3 as fallback. ***
/docker-entrypoint.sh: line 50: config/database.yml: No such file or directory

this commond runing error.
but i  update commond: 
i'm run commond in terminal :`    sudo docker run -d --name redmine -p 8000:3000 -v /mnt/data/redmine:/usr/src/redmine/files redmine:passenger` 

this commond is success!
why? 

because the Dockerfile define 
`VOLUME /usr/src/redmine/files` ?

**Comment by yosifkit** [comment]
Yes, if your mount (`-v` flag) is on `/usr/src/redmine` it will hide anything already in the image which includes all of the redmine source code.
