### ISSUE TITLE
Redmine docker container staying in Restart loop after docker pull

### ISSUE THREAD

**Issue by HigH-HawK** [docker-library/redmine#290]
Hi,

I have done a `docker-compose pull` to pull the latest images, then removed the old containers and launched new ones from the new images I just pulled.

The MySQL container is working fine but the Redmine one stays in a Restart Loop. When I do `docker logs redmine` I get the following information. I assume something is not right with either the Ruby or Rails version coming with the docker image but I am not exactly sure what is going on because I thought pulling the new image and launching it as container should work out of the box.

Error log

```
Your Gemfile lists the gem httpclient (>= 0) more than once.
You should probably keep only one of them.
Remove any duplicate entries and specify the gem only once.
While it's not a problem now, it could cause errors if you change the version of one of them later.
Your Gemfile lists the gem puma (>= 0) more than once.
You should probably keep only one of them.
Remove any duplicate entries and specify the gem only once.
While it's not a problem now, it could cause errors if you change the version of one of them later.
The Gemfile's dependencies are satisfied
rake aborted!
NoMethodError: undefined method `represent_boolean_as_integer=' for nil:NilClass

    config.active_record.sqlite3.represent_boolean_as_integer = true
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/usr/src/redmine/config/application.rb:60:in `<class:Application>'
/usr/src/redmine/config/application.rb:24:in `<module:RedmineApp>'
/usr/src/redmine/config/application.rb:20:in `<top (required)>'
<internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/usr/src/redmine/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)
```

What can I do and/or what other information could I provide?

Thank you in advance

//EDIT: These are the versions I am coming from:

<img width="635" alt="Screenshot 2023-06-06 at 19 13 55" src="https://github.com/docker-library/redmine/assets/33863449/ed1dd2a5-90ff-4a91-9ac1-11f81efc2c4a">

**Comment by tianon** [comment]
Interesting - my best bet is something weird in your configuration, previous data, or otherwise an environment issue, but it's hard to say for sure.

For every image update, we run https://github.com/docker-library/official-images/blob/de7c332aa7a4cfe75a337c30b9ec81f5becc5199/test/tests/redmine-basics/run.sh which verifies that Redmine does start up successfully and generally works.
