### ISSUE TITLE
how to install new redmine plugin for container redmine

### ISSUE THREAD

**Issue by 17635386421** [docker-library/redmine#291]
I always fail

**Comment by yosifkit** [comment]
Closing as "can't reproduce". There is not enough information here to replicate the failure.

**Comment by 17635386421** [comment]
ArgumentError: parent directory is world writable, Bundler::FileUtils#remove_entry_secure does not work; abort: "/usr/local/bundle/gems/ox-2.14.16" (parent directory mode 40777)
