### ISSUE TITLE
How to install plugins in redmine containers

### ISSUE THREAD

**Issue by 17635386421** [docker-library/redmine#292]

**Comment by 17635386421** [comment]
ArgumentError: parent directory is world writable, Bundler::FileUtils#remove_entry_secure does not work; abort: "/usr/local/bundle/gems/ox-2.14.16" (parent directory mode 40777)

**Comment by SECtim** [comment]
For anyone having this issue: A workaround is to build your own `Dockerfile` based on one of the Redmine images, and include `RUN chmod +t -R /tmp` there.
Also, for native gems (depending on which one), you may need something like
```Dockerfile
RUN update-ca-certificates && \
    apt-get update && \
    apt-get -y install build-essential dh-autoreconf
```

**Comment by LaurentGoderre** [comment]
Having build tools in the container is not ideal for security. Ideally this would be done via a multi stage build.

**Comment by LaurentGoderre** [comment]
Something like:

```Dockerfile
FROM ruby:3.1 as plugins

RUN set -e; \
    mkdir /temp_gem; \
    apt-get update;\
    apt-get -y install build-essential dh-autoreconf

ENV GEM_HOME /temp_gem

RUN set -e; \
    cd /tmp; \
    curl -sSL some_plugin -o some_plugin.tar.gz; \
    tar -xvzf some_plugintar.gz --strip-components=1 > /dev/null; \
    bundle install

FROM redmine

COPY --from=plugins /temp_gem/ /usr/local/bundle/
COPY --from=plugins /tmp/* /usr/src/redmine
```
