### ISSUE TITLE
Container don't work with mysql and another DB user instead of root

### ISSUE THREAD

**Issue by henderbj** [docker-library/redmine#3]
Thanks in advance for maintaining this docker image. If I start this container linking against a mysql container that has environment variables MYSQL_ROOT_PASSWORD and MYSQL_DATABASE, the redmine container works well.

Good commands:
```
$ docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=MyRootPass -e MYSQL_DATABASE=redmine -d mysql:5.7.8
$ docker run -ti --name some-redmine --link some-mysql:mysql redmine
```

But, If besides those two environment variables I add MYSQL_USER and MYSQL_PASSWORD when creating the mysql container, the redmine container doesn't work, giving a lot of errors:
```
...
Mysql2::Error: SELECT command denied to user 'redmine'@'172.17.0.48' for table 'session_variables'
...
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

Bad commands:
```
$ docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=MyRootPass -e MYSQL_DATABASE=redmine -e MYSQL_USER=redmine -e MYSQL_PASSWORD=MyUserPass -d mysql:5.7.8
$ docker run -ti --name some-redmine --link some-mysql:mysql redmine
```

**Comment by stront90** [comment]
Solution for postgres (you must create user and database redmine, grant rights, etc):
    .....
    --env 'POSTGRES_ENV_POSTGRES_USER=redmine' \
    --env 'POSTGRES_ENV_POSTGRES_PASSWORD=******' \
    ....
should work with mysql too (swaps env from linked db container - not elegant but works for now).

**Comment by henderbj** [comment]
Thanks for reply, stront90. The problem is related to an Mysql update on show_compatibility_56 variable, as can be seen on the following links:
http://stackoverflow.com/questions/32053655/command-denied-for-table-session-variables
http://planet.mysql.com/entry/?id=5991741

From there, you can read:
"As per these articles, Workaround is setting show_compatibility_56 = on in /etc/my.cnf and restart mysql server."

I will test later on my own if this really solve the problem. Possibly another person can test and publish results here.
