### ISSUE TITLE
Enable HTTPS without passenger

### ISSUE THREAD

**Issue by lmoellendorf** [docker-library/redmine#300]
I used the passenger image because it was the only way I found to use HTTPS:

- https://github.com/docker-library/redmine/issues/207
- https://github.com/docker-library/redmine/issues/4#issuecomment-149335151

Is there any documentation on how to enable HTTPS without passenger?

_Originally posted by @lmoellendorf in https://github.com/docker-library/redmine/issues/288#issuecomment-1723588441_

**Comment by LaurentGoderre** [comment]
You could use a reverse proxy in a separate container such as Traefik. This way the SSL config is decoupled from the app

**Comment by tianon** [comment]
https://stackoverflow.com/a/55464729/433558 is really relevant :eyes: :see_no_evil:
