### ISSUE TITLE
No 4.2.11 image

### ISSUE THREAD

**Issue by hagaygo** [docker-library/redmine#301]
Hi 

It seems 4.2.11 image is not available on docker hub , any reason for this ?

Thanks in advance

**Comment by LaurentGoderre** [comment]
Version 4 stopped being updated when the underlying version of Ruby became EOL https://github.com/docker-library/redmine/commit/8fb25e7a3f1a51010d9efcb857aed077c265f054

**Comment by hagaygo** [comment]
So no more 4.2.x docker images releases will be made ?

I can understand the reasoning , but if redmine still releases 4.2.x why not just keeping releasing docker images for those who cant/wont upgrade to 5.0.x ?

Thanks for your answers so far.

**Comment by yosifkit** [comment]
Ruby 2.7 was eol: https://github.com/docker-library/redmine/issues/289 and so we had to drop Redmine 4.2: https://github.com/docker-library/redmine/pull/294

Redmine 4.2 is now also EOL.
