### ISSUE TITLE
Redmine Docker Container fail to run

### ISSUE THREAD

**Issue by ajmalbaba** [docker-library/redmine#33]
Using MySql as database

Part of Logs while running redmine container

........
/usr/local/bundle/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/local/bundle/gems/railties-4.2.6/lib/rails/initializable.rb:54:in`run_initializers'
/usr/local/bundle/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
/usr/src/redmine/config/environment.rb:14:in`<top (required)>'
/usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in`block in require'
/usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in`require'
/usr/local/bundle/gems/railties-4.2.6/lib/rails/application.rb:328:in `require_environment!'
/usr/local/bundle/gems/railties-4.2.6/lib/rails/application.rb:457:in`block in run_tasks_blocks'
**/usr/local/bundle/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)**

Any help will be appreciated.
Thanks

**Comment by maximkrusina** [comment]
@ajmalbaba is this still an issue? Can I help?

**Comment by wglambert** [comment]
Closing since this doesn't seem to be an error with the image
