### ISSUE TITLE
Can't download Passenger native support

### ISSUE THREAD

**Issue by theblackhole** [docker-library/redmine#35]
Hello,

The **redmine:passenger** image doesn't work : it can't download passenger 5.0.30 because the urls are unreachable. 
I also tried on my pc and it's the same : 404 for the first one and 403 for the mirror.

**Edit :** it seems like the latest available version of **rubyext-ruby** is 2.2.3 not 2.2.5 : https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/5.0.30/

Logs :

```
root@7a3f2f7b3460:/usr/src/redmine/log# cat passenger.3000.log
[ 2016-08-30 12:47:49.9388 35/7f7300998740 age/Wat/WatchdogMain.cpp:1291 ]: Starting Passenger watchdog...
[ 2016-08-30 12:47:49.9441 38/7ff5bc714740 age/Cor/CoreMain.cpp:982 ]: Starting Passenger core...
[ 2016-08-30 12:47:49.9444 38/7ff5bc714740 age/Cor/CoreMain.cpp:235 ]: Passenger core running in multi-application mode.
[ 2016-08-30 12:47:49.9459 38/7ff5bc714740 age/Cor/CoreMain.cpp:732 ]: Passenger core online, PID 38
[ 2016-08-30 12:47:49.9519 43/7fbfaaa80740 age/Ust/UstRouterMain.cpp:529 ]: Starting Passenger UstRouter...
[ 2016-08-30 12:47:49.9525 43/7fbfaaa80740 age/Ust/UstRouterMain.cpp:342 ]: Passenger UstRouter online, PID 43
App 76 stdout:
App 76 stderr:  [passenger_native_support.so] trying to compile for the current user (redmine) and Ruby interpreter...
App 76 stderr:
App 76 stderr:      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
App 76 stderr:
App 76 stderr:      Warning: compilation didn't succeed. To learn why, read this file:
App 76 stderr:
App 76 stderr:      /tmp/passenger_native_support-1qr8uj8.log
App 76 stderr:
App 76 stderr:  [passenger_native_support.so] finding downloads for the current Ruby interpreter...
App 76 stderr:
App 76 stderr:      (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
App 76 stderr:
App 76 stderr:      Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/5.0.30/rubyext-ruby-2.2.5-x86_64-linux.tar.gz: The requested URL returned error: 404 Not Found
App 76 stderr:      Trying next mirror...
App 76 stderr:      Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/5.0.30/rubyext-ruby-2.2.5-x86_64-linux.tar.gz: The requested URL returned error: 403 Forbidden
App 76 stderr:  [passenger_native_support.so] will not be used (can't compile or download)
App 76 stderr:
App 76 stderr:   --> Passenger will still operate normally.
App 76 stderr:
App 76 stderr: /usr/local/bundle/gems/htmlentities-4.3.1/lib/htmlentities/mappings/expanded.rb:465: warning: duplicated key at line 466 ignored: "inodot"
App 100 stdout:
```

**Comment by yosifkit** [comment]
That looks like passenger `5` does not support the latest version of ruby 2.2 (2.2.5). :cry:  Though it looks like `5.0.x` has never supported Ruby `2.2`: https://blog.phusion.nl/2015/03/04/phusion-passenger-5-0-1-released/#minimumrailsversionisnow23.

@tianon and I think that we'll bump to Ruby 2.3 for Redmine 3.3 and then downgrade to passenger 4 for `3.2` and 3.1`.

**Comment by theblackhole** [comment]
Hi ! Sorry I was wrong, after investigation, the native support isn't required for passenger to work. :)
So after fixing some problems on my host config **redmine:passenger** does work fine and without this binary.
Apparently there is just a tiny performance decrease without it : https://solidfoundationwebdev.com/blog/posts/error-skipping-compiling-of-passenger_native_support-so-with-passenger.

Btw, in the link you've provided, they are talking about rails 2.3 not ruby 2.3 ;)

**Comment by theblackhole** [comment]
Also I've tried targeting ruby 2.2.3 directly since it's the latest version available : theblackhole/redmine@03ad48d947c046335aeb7b15e9b08a5a79941579
But some libraries are missing (I have added them on the apt section of the Dockerfile but it wasn't enough) _(sorry I've not committed all the tests on my fork because this was a huge mess :laughing: and then I've resolved my config issue)._

**Comment by yosifkit** [comment]
Oh I see... silly me. :disappointed:

Regardless of my apparent lack of comprehension, do you think we should change the versions as I described? Or maybe target a more specific version of ruby?

**Comment by theblackhole** [comment]
Sorry I'm not a ruby expert but I will answer the best as I can ^^

Right now, if we doesn't solve this low priority issue with the native extension (by targeting a more specific version + doing something to fix these .so libraries issue), it think it isn't needed to target a more specific version to work well.
However since [redmine 3.3 supports ruby 2.3](http://www.redmine.org/projects/redmine/wiki/RedmineInstall) I think it's harmless to bump to 2.3 for this version.
Also, I don't think a downgrade is required for redmine <3.3 because the 3.x branch uses rails 4.2. So it fits the passenger requirement ([rails >2.3](https://blog.phusion.nl/2015/03/04/phusion-passenger-5-0-1-released/#minimumrailsversionisnow23)) ( #headache #SoManySimilarVersions xD )

**Comment by yosifkit** [comment]
Closing old issue. I don't see anything actionable.
