### ISSUE TITLE
SSL cert question

### ISSUE THREAD

**Issue by hannen** [docker-library/redmine#4]
Hello,  I have tried searching for this info but can't find it anywhere.

Is there a process for configuring a redmine container to use a SSL cert?

Thanks.

**Comment by md5** [comment]
If you use the `redmine:passenger` image, you can follow the instructions here: https://www.phusionpassenger.com/library/config/standalone/reference/#--ssl-ssl

If you're using the `redmine` image, it appear to use WEBrick, which isn't recommended for production use. You can look at the WEBrick HTTPS instructions here: http://ruby-doc.org/stdlib-2.1.1/libdoc/webrick/rdoc/WEBrick.html#module-WEBrick-label-HTTPS

You'll probably just want to set up an Nginx proxy in front of the image and have it handle HTTPS, but in all honesty you should use `redmine:passenger` instead.

**Comment by md5** [comment]
An example command could look like this:

```console
$ docker run -d -v /path/to/my/ssl:/etc/ssl/redmine:ro \
    -p 80:3000 -p 443:3443 --expose 3443 \
    --link some-mysql:mysql redmine:passenger \
    passenger start --ssl \
        --ssl-certificate /etc/ssl/redmine/server.pem \
        --ssl-certificate-key /etc/ssl/redmine/server.key \
        --ssl-port 3443
```

**Comment by hannen** [comment]
Thanks so much for your help.
