### ISSUE TITLE
Avoid "config/database.yml first" problem

### ISSUE THREAD

**Issue by imaia** [docker-library/redmine#51]
How to avoid the:
"Please configure your config/database.yml first"

When "running" commands with the official redmine container?

**Comment by yosifkit** [comment]
What commands are you running and how are you running them?

As long as you are only setting the `CMD`, and using rails, rake, or passenger, then the entrypoint script will [configure the database.yml for you](https://github.com/docker-library/redmine/blob/e803be4f45b5db05ea950d2e2831f1811df8f488/docker-entrypoint.sh#L27-L90) based on the environment.

So, something like `docker run -it --rm -v /path/to/my/files:/usr/src/redmine/files -e REDMINE_DB_MYSQL=mysql -e ... redmine:3.3 rake db:migrate` should work.
