### ISSUE TITLE
Running multiple commands in entrypoint

### ISSUE THREAD

**Issue by imaia** [docker-library/redmine#52]
I'm trying to copy some files before running my entrypoint script. I tried something like this in my docker-compose.yml:

entrypoint: ["sh", "-c", "cp -r /usr/src/redmine/public/. /www/public/ && /docker-entrypoint.sh"]

But I'm getting a exit code 0. Suggestions?

**Comment by abcfy2** [comment]
You don't need to modify `entrypoint`, just set `command`.
```yaml
    command:
      - /bin/sh
      - -c
      - |
          bundle config mirror.https://rubygems.org https://gems.ruby-china.org
          bundle exec rake redmine:plugins:migrate RAILS_ENV=production
          bundle exec rake tmp:cache:clear tmp:sessions:clear RAILS_ENV=production
          /docker-entrypoint.sh passenger start
```

`YAML` supports multiline string.

**Comment by jadekler** [comment]
Awesome solution @abcfy2

**Comment by tianon** [comment]
Closing, given the excellent solution posted above. :+1:

(The only change I'd personally make is adding `exec` before the invocation of `/docker-entrypoint.sh` to ensure the outer shell process gets ditched and Redmine properly becomes PID 1.)

**Comment by jmdxy** [comment]
/bin/sh: 1: bundle: not found
