### ISSUE TITLE
ImageMagick error when executing png gantt

### ISSUE THREAD

**Issue by Angelinsky7** [docker-library/redmine#65]
If you try to extract a gantt in png format redmine does this error :
```
app_1  | Magick::ImageMagickError (unable to read font `' @ error/annotate.c/RenderFreetype/1127: `(null)'):
app_1  |   lib/redmine/helpers/gantt.rb:436:in `draw'
app_1  |   lib/redmine/helpers/gantt.rb:436:in `to_image'
app_1  |   app/controllers/gantts_controller.rb:44:in `block (2 levels) in show'
app_1  |   app/controllers/gantts_controller.rb:42:in `show'
app_1  |   lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```
It seems that it would be related to the fact that ghostscript is missing from the installation (from https://github.com/turnkeylinux/tracker/issues/633)

Sadly it's hard for me to check if it's correct.
Anyone with the same issue ?

Thanks

**Comment by tianon** [comment]
Do you have a simple set of steps that can be used to reproduce the issue? :innocent: :pray:

**Comment by Angelinsky7** [comment]
I am really sorry....
i was copy/pasting my config file when i saw in the configuration.yml file those lines :

`rmagick_font_path:`

i just tried to set a correct path like 

`rmagick_font_path: /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf`

and everything is working fine now.
So sorry for the bad issue
And thanks for coming asking questions (angel)

**Comment by ociotec** [comment]
I had also this issue with latest version (the one with Redmine v3.4.2), but after checking that I had empty `rmagick_font_path` variable, I tested to manually install ghostscript with:

    sudo apt update && sudo apt install -y ghostscript

and it worked! but I know that this is just a workarround, as soon as I delete the container...

Is there something wrong with my setup? Is this happening to others?

Thanks in advance.
