### ISSUE TITLE
sendmail not installed

### ISSUE THREAD

**Issue by patrel** [docker-library/redmine#66]
Hey guys,

I tried to send notification mails via smtp and got the following error:
 `sh: 1: /usr/sbin/sendmail: not found`

Wouldn't it be nice to have it preinstalled within the container?

Regards
patrel

**Comment by docqube** [comment]
+1

**Comment by pwFoo** [comment]
Maybe it should be a separated container deployed with docker-compose?

**Comment by tianon** [comment]
Sorry for the delay.

Setting up Docker images to be able to successfully send email by default is a very tricky proposition -- there's a lot involved in doing so properly, and it'll change based on each user's environment.

As for the direct issue, installing sendmail in your own image should be as simple as a 2-line `Dockerfile` something like this:

```dockerfile
FROM redmine:X.Y

RUN apt-get update && apt-get install -y --no-install-recommends sendmail
```

**Comment by maximkrusina** [comment]
Just my opinion: it's much better to use some external server and those days it's very important to have properly configured both SPF and DKIM records, otherwise there is big chance that your notifications will end in some spam folder.
