### ISSUE TITLE
Image depends on --link specific env vars

### ISSUE THREAD

**Issue by AngCaruso** [docker-library/redmine#69]
This image seems to be dependent on environment variables that are automatically defined under the hood when using the deprecated Docker --link option.

To get this to work with Postgres using Docker networks, which I understand to be the recommended approach (instead of the --link option), the following environment variables must be available to the Redmine container:
REDMINE_DB_POSTGRES (set to the name of the Postgres container)
POSTGRES_ENV_POSTGRES_USER
POSTGRES_ENV_POSTGRES_PASSWORD

The last two are created (and set appropriately) by Docker when using the --link option.  The dependency on these env vars needs to be documented, along with an explanation that they must be explicitly defined for the container when not using the --link option.

This also applies when using docker-compose: the env vars must be specified in the yml file.

**Comment by yosifkit** [comment]
There have been proper env variables since #24, but they were not documented. :disappointed:  I made a PR to fix that: https://github.com/docker-library/docs/pull/906 :smiley_cat:
