### ISSUE TITLE
when I choose the 'simplified chinese' to load the default the configuration ,it doesn't work

### ISSUE THREAD

**Issue by huangsj47** [docker-library/redmine#71]
The default setting could not be loaded：Mysql2::Error: Incorrect string value: '\xE7\xAE\xA1\xE7\x90\x86...' for column 'name' at row 1: INSERT INTO roles (name, issues_visibility, position) VALUES ('管理人员', 'all', 1)

**Comment by yosifkit** [comment]
Did you set your database to be utf8? Example for MySQL [here](https://github.com/docker-library/docs/tree/2063b7e17d9ace103a5afd1a2b2a3db54f9a455f/mysql#configuration-without-a-cnf-file).
