### ISSUE TITLE
Error extracting image

### ISSUE THREAD

**Issue by Richard-Payne** [docker-library/redmine#72]
I try to pull the "redmine" image and get this:

![screenshot at 2017-06-03 19-42-15](https://cloud.githubusercontent.com/assets/6730730/26756201/ef59f514-4894-11e7-98dd-6a0369487f84.png)

**Comment by Richard-Payne** [comment]
Actually, that wasn't quite true.  That error came during a docker-compose up call.  If I run docker pull directly then it works.  docker-compose then executes properly.

**Comment by yosifkit** [comment]
That would've been a docker or docker hub issue, not anything wrong with the image itself.
