### ISSUE TITLE
3.3.4 fails to init due to mysql2 gem

### ISSUE THREAD

**Issue by amarokete** [docker-library/redmine#78]
After a container restart today our Redmine 3.3.4 with MySQL backend is breaking due to the following error:

```Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory: /usr/local/bundle/gems/mysql2-0.4.8/ext/mysql2
/usr/local/bin/ruby -r ./siteconf20170711-7-l14zoc.rb extconf.rb
checking for rb_absint_size()... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/local/bin/$(RUBY_BASE_NAME)
/usr/local/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to
generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:541:in `try_link0'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:556:in `try_link'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:735:in `try_func'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:1020:in `block in have_func'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:321:in `open'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:321:in `open'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:1019:in `have_func'
        from extconf.rb:26:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

  /usr/local/bundle/extensions/x86_64-linux/2.2.0/mysql2-0.4.8/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/bundle/gems/mysql2-0.4.8 for
inspection.
Results logged to
/usr/local/bundle/extensions/x86_64-linux/2.2.0/mysql2-0.4.8/gem_make.out

An error occurred while installing mysql2 (0.4.8), and Bundler cannot continue.
Make sure that `gem install mysql2 -v '0.4.8'` succeeds before bundling.

In Gemfile:
  mysql2
```
Redmine 3.3.3 (which uses a different myql2 gem version) still boots properly. 

Seems mysql2 0.4.8 gem version has been recently released and is being now used by Redmine ("~> 0.4.6"). A Dockerfile update my be needed to include a new MySQL client dependency.

**Comment by LJBD** [comment]
Same issue happening to me.
This seems to be the same issue reported as #21, but it hasn't been resolved - there's only a workaround and it doesn't work for `docker-compose`.

**Comment by yosifkit** [comment]
Any details about how this is deployed so that we can reproduce it?  Contents of `docker-compose.yml` or `docker run` lines?

**Comment by marouanabbessi** [comment]
I have the same problem when running the latest version of redmine today  : 

> docker run -d --name redmine --link mysql:mysql -p 3000:3000  redmine

**Comment by pmietlicki** [comment]
Hi,
Same problem here.

**Comment by LJBD** [comment]
> Any details about how this is deployed so that we can reproduce it? Contents of docker-compose.yml or docker run lines?

Oh, sorry, I've forgotten to add that. I've used the example that is in the image's description on DockerHub:

```yaml
version: '3.1'

services:

  redmine:
    image: redmine
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
```

I've put that in a `docker-compose.yml` and tried to `up` it.

**Comment by marouanabbessi** [comment]
I build a redmine image from the 3.3 version  metadata, and it works fine for me

**Comment by amarokete** [comment]
Building a new 3.3.4 redmine image from the Dockerfile works well. The one uploaded to Dockerhub fails to run due to the mentioned error.

**Comment by wefixit-AT** [comment]
Can anybody please update the files from Dockerhub, so we can use redmine again

**Comment by yosifkit** [comment]
Should be fixed by #80. We'll get an update PR to official-images shortly.

**Comment by LJBD** [comment]
@yosifkit - thanks a lot!
Could you please define "shortly"? Is it a matter of days or weeks?

**Comment by yosifkit** [comment]
Shortly, as in, it was merged in https://github.com/docker-library/official-images/pull/3194 on 13 July 2017, 4:06 PM PDT and is available on the Docker Hub.

**Comment by LJBD** [comment]
@yosifkit - all right, thanks again!
I was asking because I've seen the same error yesterday, but it turned out that I haven't configured my MySQL container properly and now everything is fine.

**Comment by marouanabbessi** [comment]
Thanks for the update ..

**Comment by amarokete** [comment]
Working again. Thanks!
