### ISSUE TITLE
Merge up with our repo.

### ISSUE THREAD

**Issue by frank-dspeed** [docker-library/redmine#90]
Hi i am Maintainer of this
- https://github.com/sameersbn/docker-redmine

Tianon we know us from the early docker days lets partner up and merge all our stuff that usefull into your image and maintain it together we have much done in start scripts already and also want to refactor to external nginx so this would be a ideal fit. maybe we could meet on irc for discussion? what do you think?

**Comment by yosifkit** [comment]
Looking over the image I am not sure I see where they could be merged.  There seems to be a lot of code dealing with automation and config management in your image, where we try to stick to a minimal image that can be extended.  We'd definitely not want an image in official-images that includes supervisor to run multiple services in one container.

**Comment by frank-dspeed** [comment]
@yosifkit we also don't want that anymore :+1: but your right we should use your image as base image and put our automation on top maybe

**Comment by tianon** [comment]
Glad to see this was resolved. :+1:
