### ISSUE TITLE
Suggestion: Add HEALTHCHECK?

### ISSUE THREAD

**Issue by fdcastel** [docker-library/redmine#93]
There are any plans to implement [HEALTHCHECK](https://docs.docker.com/engine/reference/builder/#healthcheck) in this image?

**Comment by tianon** [comment]
Not at present; see https://github.com/docker-library/cassandra/pull/76#issuecomment-246054271

> I do not feel that generalized healthchecks on the official images are really that useful. 
>- users will have their own idea of what is "healthy"
>- it does not actually test that the service is listening to connections outside of `localhost` (see https://github.com/docker-library/healthcheck for some examples that do more than what's proposed here, including attempting to check whether the service is listening remotely)
>   - some of the Official Images even purposely start in a `localhost` only mode for database initialization and then kill and start the main service with full network availability
>- after upgrading their images, current users will have extra unexpected load on their systems for healthchecks they don't necessarily need/want and may be unaware of
