### ISSUE TITLE
Docker container hanging after some time

### ISSUE THREAD

**Issue by fmello-cit** [docker-library/redmine#97]
Hi, I created a redmine container, all default except for database config:

sudo docker run -d --name my-redmine -p 3000:3000 -e REDMINE_DB_MYSQL=mydbhost -e REDMINE_DB_USERNAME=redmine -e REDMINE_DB_PASSWORD=mupasswd -e REDMINE_DB_DATABASE=redmine redmine

It works perfectly, for about 30 minutes.
After using redmine for 30 minutes, it stops responding, and that's it.
Checking container logs, no errors, everything looks fine, if I restart the container, it works for more 30 minutes.
Logs after hanging:

`The Gemfile's dependencies are satisfied
[2017-11-23 15:18:22] INFO  WEBrick 1.3.1
[2017-11-23 15:18:22] INFO  ruby 2.2.8 (2017-09-14) [x86_64-linux]
[2017-11-23 15:18:22] INFO  WEBrick::HTTPServer#start: pid=1 port=3000`

I created another container using redmine:3.3, and I got the same problem.

My VM is hosted on azure, has 1 cpu, with 1,75 Gb of memory ram.

Any clues about this problem?

Thanks!

**Comment by ToniIltanen** [comment]
I had the same problem, my assume was that webrick has shutted down. Now i am trying with passenger, but the swarm task returns status **complete**, and the swarm service is shutted down when passenger start is called.

**Comment by tianon** [comment]
Hmm, any clues in `docker stats` for the relevant container? (perhaps a memory leak or something?)

**Comment by tianon** [comment]
Since we can't reliably reproduce this (and it doesn't seem to be something related to the image and thus something we could fix), I'm going to close.  If we can create a reliable reproducer _and_ determine that this is something specific to the image (not an upstream issue), opening a new issue (or PR!) with more detail would be great. :+1:
